; rmt_ata.s - ca65 version of asm/Legacy/rmt_ata.a65
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;
;3000, 3400
.ifndef STEREOMODE
STEREOMODE = 1
.endif
	.include "rmt.s"

;3d00		a=note0-63,x=trackindex0-7,y=instrument0-63
	ORG	$3d00
	sta	trackn_note,x	;nastavi trackn_note
.if FEAT_BASS16
	sta	trackn_outnote,x	;(pokud by ji uz nicim nezmenil, zustane stejna jako note)
.endif
	tya
	asl	a
	sta	trackn_instrx2,x
	bmi	usi1	;je-li cislo instrumentu*2 >127 => neprovede nastaveni instrumentu (kvuli kompatibilite s rutinou)
	tay
	jmp	SetUpInstrumentY2	;v y je cislo instrumentu *2, v x je cislo tracku
	;jsr-rts
usi1 = *
	rts

	ORG	xata_rtshere	;prepsani kodu RMT rutiny tak aby se SetUpInstrumentY2 dal volat jako podprogram
	rts


;3e00		a=volume0-15,x=trackindex0-7
	ORG	$3e00
	asl	a
	asl	a
	asl	a
	asl	a
	sta	trackn_volume,x	;nastavi volume
	rts

;3e80		x=trackindex0-7
	ORG	$3e80
	lda	#0
	sta	trackn_volume,x	;vynuluje volume
	sta	trackn_instrhb,x	;vynuluje HB instrumentu => vypne provadeni instrumentu
	sta	trackn_instrdb,x	;vynuluje i DB (navic, jen aby nezustaval nenulovy, ale neni to potreba)
	sta	trackn_audc,x	;ztisi prislusny sound generator
	rts

;modu 3f00
	ORG	$3f00
;
INSTR = $4000
SONG = $8000
MODUL = *
;
	.byte	"RMT8"	;4b head "RMT" + "4" (4tracks mono) or "8" (8tracks stereo)
	.byte	64	;1b max track length 0-255; (0=256)
	.byte	64	;1b track speed
	.byte	1	;1b instr speed 1-4  (1=1x/vbi,2=2x/vbi,3=3x/vbi,4=4x4vbi)
	.byte	0	;1b reserved
	.word	instrumentsaddr	;2b
	.word	0	;(tracksaddrdbytes)				;2b
	.word	0	;(tracksaddrhbytes)				;2b
	.word	songaddr	;2b
;									;======= 16b
;
instrumentsaddr = *	;(pouzivaji se nejcasteji, tak aby co mozna nejmin lezly pres hranu stranky)
	.word	INSTR+$0000
	.word	INSTR+$0100
	.word	INSTR+$0200
	.word	INSTR+$0300
	.word	INSTR+$0400
	.word	INSTR+$0500
	.word	INSTR+$0600
	.word	INSTR+$0700
	.word	INSTR+$0800
	.word	INSTR+$0900
	.word	INSTR+$0a00
	.word	INSTR+$0b00
	.word	INSTR+$0c00
	.word	INSTR+$0d00
	.word	INSTR+$0e00
	.word	INSTR+$0f00
;
	.word	INSTR+$1000
	.word	INSTR+$1100
	.word	INSTR+$1200
	.word	INSTR+$1300
	.word	INSTR+$1400
	.word	INSTR+$1500
	.word	INSTR+$1600
	.word	INSTR+$1700
	.word	INSTR+$1800
	.word	INSTR+$1900
	.word	INSTR+$1a00
	.word	INSTR+$1b00
	.word	INSTR+$1c00
	.word	INSTR+$1d00
	.word	INSTR+$1e00
	.word	INSTR+$1f00
;
	.word	INSTR+$2000
	.word	INSTR+$2100
	.word	INSTR+$2200
	.word	INSTR+$2300
	.word	INSTR+$2400
	.word	INSTR+$2500
	.word	INSTR+$2600
	.word	INSTR+$2700
	.word	INSTR+$2800
	.word	INSTR+$2900
	.word	INSTR+$2a00
	.word	INSTR+$2b00
	.word	INSTR+$2c00
	.word	INSTR+$2d00
	.word	INSTR+$2e00
	.word	INSTR+$2f00
;
	.word	INSTR+$3000
	.word	INSTR+$3100
	.word	INSTR+$3200
	.word	INSTR+$3300
	.word	INSTR+$3400
	.word	INSTR+$3500
	.word	INSTR+$3600
	.word	INSTR+$3700
	.word	INSTR+$3800
	.word	INSTR+$3900
	.word	INSTR+$3a00
	.word	INSTR+$3b00
	.word	INSTR+$3c00
	.word	INSTR+$3d00
	.word	INSTR+$3e00
	.word	INSTR+$3f00
;
;...
;
;tracksaddr
;	dta a(track00)
;...
;
songaddr = *
	.byte	255, 255, 255, 255, 255, 255, 255, 255
	;254=go,line=0,adrline0=songaddr
	.byte	254, 0
	.word	songaddr
;...
