; rmt_feat_full.s - ca65 version of asm/Legacy/rmf/rmt_feat_full.a65
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;*
;* RMT FEATures definitions
;* For optimizations of RMT player routine to concrete RMT modul only!
;* --------BEGIN--------
;* cca 8 bytes
.ifndef FEAT_COMMAND1
FEAT_COMMAND1 = 1
.endif
;* cca 20 bytes (+save 1 address in zero page) and quicker whole RMT routine
.ifndef FEAT_COMMAND2
FEAT_COMMAND2 = 1
.endif
;* cca 12 bytes
.ifndef FEAT_COMMAND3
FEAT_COMMAND3 = 1
.endif
;* cca 15 bytes
.ifndef FEAT_COMMAND4
FEAT_COMMAND4 = 1
.endif
;* cca 67 bytes
.ifndef FEAT_COMMAND5
FEAT_COMMAND5 = 1
.endif
;* cca 15 bytes
.ifndef FEAT_COMMAND6
FEAT_COMMAND6 = 1
.endif
;* COMMAND7 SETNOTE (i.e. command 7 with parameter != $80)
;* cca 12 bytes
.ifndef FEAT_COMMAND7SETNOTE
FEAT_COMMAND7SETNOTE = 1
.endif
;* COMMAND7 VOLUMEONLY (i.e. command 7 with parameter == $80)
;* cca 74 bytes
.ifndef FEAT_COMMAND7VOLUMEONLY
FEAT_COMMAND7VOLUMEONLY = 1
.endif
;* PORTAMENTO
;* cca 138 bytes and quicker whole RMT routine
.ifndef FEAT_PORTAMENTO
FEAT_PORTAMENTO = 1
.endif
;* FILTER
;* cca 179 bytes and quicker whole RMT routine
.ifndef FEAT_FILTER
FEAT_FILTER = 1
.endif
;* (cca 38 bytes for each)
.ifndef FEAT_FILTERG0L
FEAT_FILTERG0L = 1
.endif
.ifndef FEAT_FILTERG1L
FEAT_FILTERG1L = 1
.endif
.ifndef FEAT_FILTERG0R
FEAT_FILTERG0R = 1
.endif
.ifndef FEAT_FILTERG1R
FEAT_FILTERG1R = 1
.endif
;* BASS16B (i.e. distortion value 6)
;* cca 194 bytes +128bytes freq table and quicker whole RMT routine
.ifndef FEAT_BASS16
FEAT_BASS16 = 1
.endif
;* (cca 47 bytes for each)
.ifndef FEAT_BASS16G1L
FEAT_BASS16G1L = 1
.endif
.ifndef FEAT_BASS16G3L
FEAT_BASS16G3L = 1
.endif
.ifndef FEAT_BASS16G1R
FEAT_BASS16G1R = 1
.endif
.ifndef FEAT_BASS16G3R
FEAT_BASS16G3R = 1
.endif
;* VOLUME ONLY for particular generators
;* (cca 7 bytes for each)
.ifndef FEAT_VOLUMEONLYG0L
FEAT_VOLUMEONLYG0L = 1
.endif
.ifndef FEAT_VOLUMEONLYG2L
FEAT_VOLUMEONLYG2L = 1
.endif
.ifndef FEAT_VOLUMEONLYG3L
FEAT_VOLUMEONLYG3L = 1
.endif
.ifndef FEAT_VOLUMEONLYG0R
FEAT_VOLUMEONLYG0R = 1
.endif
.ifndef FEAT_VOLUMEONLYG2R
FEAT_VOLUMEONLYG2R = 1
.endif
.ifndef FEAT_VOLUMEONLYG3R
FEAT_VOLUMEONLYG3R = 1
.endif
;* TABLE TYPE (i.e. TABLETYPE=1)
;* cca 53 bytes and quicker whole RMT routine
.ifndef FEAT_TABLETYPE
FEAT_TABLETYPE = 1
.endif
;* TABLE MODE (i.e. TABLEMODE=1)
;* cca 16 bytes and quicker whole RMT routine
.ifndef FEAT_TABLEMODE
FEAT_TABLEMODE = 1
.endif
;* TABLE GO (i.e. TGO is nonzero value)
;* cca 6 bytes and quicker whole RMT routine
.ifndef FEAT_TABLEGO
FEAT_TABLEGO = 1
.endif
;* AUDCTLMANUALSET (i.e. any MANUAL AUDCTL setting is nonzero value)
;* cca 27 bytes and quicker whole RMT routine
.ifndef FEAT_AUDCTLMANUALSET
FEAT_AUDCTLMANUALSET = 1
.endif
;* VOLUME MINIMUM (i.e. VMIN is nonzero value)
;* cca 12 bytes and quicker whole RMT routine
.ifndef FEAT_VOLUMEMIN
FEAT_VOLUMEMIN = 1
.endif
;* --------END--------
