; rmt_feat_spec.s - ca65 version of asm/Legacy/rmf/rmt_feat_spec.a65
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;*
;* RMT FEATures definitions
;* For optimizations of RMT player routine to concrete RMT modul only!
;* --------BEGIN--------
;* C:\My Documents\test.rmf
;(29 times)
.ifndef FEAT_COMMAND1
FEAT_COMMAND1 = 1
.endif
;(0 times)
.ifndef FEAT_COMMAND2
FEAT_COMMAND2 = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND3
FEAT_COMMAND3 = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND4
FEAT_COMMAND4 = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND5
FEAT_COMMAND5 = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND6
FEAT_COMMAND6 = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND7SETNOTE
FEAT_COMMAND7SETNOTE = 0
.endif
;(0 times)
.ifndef FEAT_COMMAND7VOLUMEONLY
FEAT_COMMAND7VOLUMEONLY = 0
.endif
;(0 times)
.ifndef FEAT_PORTAMENTO
FEAT_PORTAMENTO = 0
.endif
;(4 times)
.ifndef FEAT_FILTER
FEAT_FILTER = 1
.endif
;(4 times)
.ifndef FEAT_FILTERG0L
FEAT_FILTERG0L = 1
.endif
;(0 times)
.ifndef FEAT_FILTERG1L
FEAT_FILTERG1L = 0
.endif
;(4 times)
.ifndef FEAT_FILTERG0R
FEAT_FILTERG0R = 1
.endif
;(0 times)
.ifndef FEAT_FILTERG1R
FEAT_FILTERG1R = 0
.endif
;(0 times)
.ifndef FEAT_BASS16
FEAT_BASS16 = 0
.endif
;(0 times)
.ifndef FEAT_BASS16G1L
FEAT_BASS16G1L = 0
.endif
;(0 times)
.ifndef FEAT_BASS16G3L
FEAT_BASS16G3L = 0
.endif
;(0 times)
.ifndef FEAT_BASS16G1R
FEAT_BASS16G1R = 0
.endif
;(0 times)
.ifndef FEAT_BASS16G3R
FEAT_BASS16G3R = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG0L
FEAT_VOLUMEONLYG0L = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG2L
FEAT_VOLUMEONLYG2L = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG3L
FEAT_VOLUMEONLYG3L = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG0R
FEAT_VOLUMEONLYG0R = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG2R
FEAT_VOLUMEONLYG2R = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEONLYG3R
FEAT_VOLUMEONLYG3R = 0
.endif
;(2 times)
.ifndef FEAT_TABLETYPE
FEAT_TABLETYPE = 1
.endif
;(0 times)
.ifndef FEAT_TABLEMODE
FEAT_TABLEMODE = 0
.endif
;(2 times)
.ifndef FEAT_TABLEGO
FEAT_TABLEGO = 1
.endif
;(0 times)
.ifndef FEAT_AUDCTLMANUALSET
FEAT_AUDCTLMANUALSET = 0
.endif
;(0 times)
.ifndef FEAT_VOLUMEMIN
FEAT_VOLUMEMIN = 0
.endif
;* --------END--------
