; rmt_feat.s - ca65 version of asm/Patch-16/rmt_feat.a65
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;*
;* RMT FEATures definitions
;*
;* For optimizations of RMT player routine to concrete RMT module only!

;* ------------------------------------------------------------------------------------------------------------

;* PATCH16 ADDITIONS BY VINSCOOL, USE ONLY IF YOU KNOW WHAT YOU ARE DOING!

;* enable ONLY if the target output is the actual RMT driver binary (tracker.obx), There are few specific changes involved!
.ifndef FEAT_IS_TRACKER
FEAT_IS_TRACKER = 1
.endif

;* Simple RMT Player is a simple recreation of the original .xex export player from RMT, enable for few bonus features
.ifndef FEAT_IS_SIMPLEP
FEAT_IS_SIMPLEP = 0
.endif

	.assert !((FEAT_IS_TRACKER+FEAT_IS_SIMPLEP)=0), error, "ERT [FEAT_IS_TRACKER+FEAT_IS_SIMPLEP]=0"	;* The RMT driver has no driver parameter defined!
	.assert !((FEAT_IS_TRACKER+FEAT_IS_SIMPLEP)=2), error, "ERT [FEAT_IS_TRACKER+FEAT_IS_SIMPLEP]=2"	;* The RMT driver could not have more than 1 driver parameter defined!

.if FEAT_IS_TRACKER	;* must be defined to work around some undefined labels...
.ifndef EXPORTXEX
EXPORTXEX = 0
.endif
.ifndef EXPORTSAP
EXPORTSAP = 0
.endif
.endif

;* ------------------------------------------------------------------------------------------------------------

;* STEREO MODE MUST ALWAYS BE 1 IF THE OUTPUT IS INTENDED FOR USE AS RMT DRIVER BINARY, ELSE IT WILL BE BROKEN!

.if FEAT_IS_TRACKER
.ifndef STEREOMODE
STEREOMODE = 1
.endif
.elseif !FEAT_IS_SIMPLEP	;* dasmplayer.asm has its own definition there so it could be ignored here 
.ifndef STEREOMODE
STEREOMODE = 0
.endif
						;* 0 => compile RMTplayer for 4 tracks mono
						;* 1 => compile RMTplayer for 8 tracks stereo
						;* 2 => compile RMTplayer for 4 tracks stereo L1 R2 R3 L4
						;* 3 => compile RMTplayer for 4 tracks stereo L1 L2 R3 R4
						;* 4 => compile RMTplayer for 8 tracks Dual Mono LR1 LR2 LR3 LR4
.endif

;* Stereo mode may also be defined from a different location (game/demo, dasmplayer.asm, etc), comment it out if necessary

;* ------------------------------------------------------------------------------------------------------------

;* --------BEGIN--------

;* 0 => No SFX support, 1 => SFX support
.ifndef FEAT_SFX
FEAT_SFX = 0
.endif
;* 0 => No RMTGLOBALVOLUMEFADE support, 1=> RMTGLOBALVOLUMEFADE support (+7 bytes)
.ifndef FEAT_GLOBALVOLUMEFADE
FEAT_GLOBALVOLUMEFADE = 0
.endif
;* 0 => Init with starting songline, 1=> no starting songline (start from songline 0 always), cca 22 or 24 bytes
.ifndef FEAT_NOSTARTINGSONGLINE
FEAT_NOSTARTINGSONGLINE = 0
.endif
;* cca 21 or 5 bytes
.ifndef FEAT_INSTRSPEED
FEAT_INSTRSPEED = 0
.endif
;* cca 28 bytes
.ifndef FEAT_CONSTANTSPEED
FEAT_CONSTANTSPEED = 0
.endif

;* ------------------------------------------------------------------------------------------------------------

;* VARIOUS COMMANDS
;* cca 8 bytes
.ifndef FEAT_COMMAND1
FEAT_COMMAND1 = 1
.endif
;* cca 20 bytes (+save 1 address in zero page) and quicker whole RMT routine
.ifndef FEAT_COMMAND2
FEAT_COMMAND2 = 1
.endif
;* cca 12 bytes
.ifndef FEAT_COMMAND3
FEAT_COMMAND3 = 1
.endif
;* cca 15 bytes
.ifndef FEAT_COMMAND4
FEAT_COMMAND4 = 1
.endif
;* cca 67 bytes
.ifndef FEAT_COMMAND5
FEAT_COMMAND5 = 1
.endif
;* cca 15 bytes
.ifndef FEAT_COMMAND6
FEAT_COMMAND6 = 1
.endif
;* patch16 addition by Vin, valid values are from $00 to $FC included 
.ifndef FEAT_COMMAND7
FEAT_COMMAND7 = 1
.endif

;* COMMAND7 Volume Only mode (command 7 with parameter == $FF)
;* patch16 change by Vin, unsure how many bytes are involved
.ifndef FEAT_VOLUME_ONLY
FEAT_VOLUME_ONLY = 1
.endif

;* COMMAND7 Two-Tone Filter toggle (command 7 with parameter == $FE to enable, $FD to disable)
;* patch16 change by Vin, unsure how many bytes are involved
.ifndef FEAT_TWO_TONE
FEAT_TWO_TONE = 1
.endif

;* PORTAMENTO
;* cca 138 bytes and quicker whole RMT routine
.ifndef FEAT_PORTAMENTO
FEAT_PORTAMENTO = 1
.endif

;* FILTER
;* cca 179 bytes and quicker whole RMT routine
.ifndef FEAT_FILTER
FEAT_FILTER = 1
.endif
;* (cca 38 bytes for each)
.ifndef FEAT_FILTERG0L
FEAT_FILTERG0L = 1
.endif
.ifndef FEAT_FILTERG1L
FEAT_FILTERG1L = 1
.endif
.ifndef FEAT_FILTERG0R
FEAT_FILTERG0R = 1
.endif
.ifndef FEAT_FILTERG1R
FEAT_FILTERG1R = 1
.endif

;* New 16-bit code, for full 16-bit support
;* patch16 addition by Vin, unsure how many bytes are involved
.ifndef FEAT_FULL_16BIT
FEAT_FULL_16BIT = 1
.endif

;* Alternative 16-bit method, which simplifies the old BASS16 method, can be used to output 16-bit frequencies using Distortion 6
;* patch16 addition by Vin, unsure how many bytes are involved
.ifndef FEAT_BASS16
FEAT_BASS16 = 1
.endif

;* New Sawtooth code, output the Sawtooth waveform, or Triangle
;* patch16 addition by Vin, unsure how many bytes are involved
.ifndef FEAT_FULL_SAWTOOTH
FEAT_FULL_SAWTOOTH = 1
.endif

;* TABLE TYPE (i.e. TABLETYPE=1)
;* cca 53 bytes and quicker whole RMT routine
.ifndef FEAT_TABLETYPE
FEAT_TABLETYPE = 1
.endif

;* TABLE MODE (i.e. TABLEMODE=1)
;* cca 16 bytes and quicker whole RMT routine
.ifndef FEAT_TABLEMODE
FEAT_TABLEMODE = 1
.endif

;* TABLE GO (i.e. TGO is nonzero value)
;* cca 6 bytes and quicker whole RMT routine
.ifndef FEAT_TABLEGO
FEAT_TABLEGO = 1
.endif

;* AUDCTLMANUALSET (i.e. any MANUAL AUDCTL setting is nonzero value)
;* cca 27 bytes and quicker whole RMT routine
.ifndef FEAT_AUDCTLMANUALSET
FEAT_AUDCTLMANUALSET = 1
.endif

;* VOLUME MINIMUM (i.e. VMIN is nonzero value)
;* cca 12 bytes and quicker whole RMT routine
.ifndef FEAT_VOLUMEMIN
FEAT_VOLUMEMIN = 1
.endif

;* INSTREUMENT EFFECTS (i.e. VIBRATO or FSHIFT are nonzero values with nonzero DELAY)
;* cca 65 bytes and quicker whole RMT routine
.ifndef FEAT_EFFECTVIBRATO
FEAT_EFFECTVIBRATO = 1
.endif
;* cca 11 bytes and quicker whole RMT routine
.ifndef FEAT_EFFECTFSHIFT
FEAT_EFFECTFSHIFT = 1
.endif
;* (btw - if no one from this two effect is used, it will save cca 102 bytes)

;* Manual tuning table loaded from instruments, this is experimental code, do not use unless you have a reason to try it out!
;* patch16 addition by Vin, unsure how many bytes are involved
.ifndef FEAT_TABLE_MANUAL
FEAT_TABLE_MANUAL = 0
.endif

;* --------END--------

