; rmtvis.s - ca65 version of asm/Patch-16/rmtvis.a65
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;******************************************************;
;* MUSIC init & play                                  *;
;* Example by Raster/C.P.U., 2003-2004                *;
;* RMT Visualizer by Pigu-A, 3-10-2018 (uncertain)    *;
;* Additions and improvements by VinsCool, 22-09-2021 *;
;* Version 0.7 - Work in Progress...                  *;
;******************************************************;

; starting line for songs when loaded, useful for playing from different lines or subtunes

.ifndef STARTLINE
STARTLINE = 0
.endif

; Stereo mode, copied over from 'rmtplayr.a65' for easier access during edit

; 0 => compile RMTplayer for 4 tracks Mono
.ifndef STEREOMODE
STEREOMODE = 0
.endif
			; 1 => compile RMTplayer for 8 tracks Stereo --Visualizer broken (temporarily)
			; 2 => compile RMTplayer for 4 tracks Stereo L1 R2 R3 L4 --Visualizer broken
			; 3 => compile RMTplayer for 4 tracks Stereo L1 L2 R3 R4 --Visualizer broken
			; 4 => compile RMTplayer for 8 tracks Dual Mono LR1 LR2 LR3 LR4

; the player is assembled as for the Simple RMT Player: in rmt_feat.a65 FEAT_IS_TRACKER equ 0 and FEAT_IS_SIMPLEP equ 1
; no XEX/SAP export hacks in the player: its XEX hack changes the rasterbar colour at loop+1, here loop is not that

.ifndef EXPORTXEX
EXPORTXEX = 0
.endif
.ifndef EXPORTSAP
EXPORTSAP = 0
.endif

; playback speed will be adjusted accordingly in the other region

; 0 => PAL
.ifndef REGIONPLAYBACK
REGIONPLAYBACK = 0
.endif
                        ; 1 => NTSC

; screen line for synchronization, important to set with a good value to get smooth execution

; 16 is the default according to Raster's example player
.ifndef VLINE
VLINE = 12
.endif

; quick workaround for debugging purpose, not a permanent option. Will be removed in the future

.ifndef DISPLAYNOTES
DISPLAYNOTES = 1
.endif

; memory addresses for a bunch of stuff

zARG0 = $f0	; screen position offset
zARG1 = $f2	; screen position offset
zTMP0 = $f8	; screen position offset
zTMP1 = $f9	; POKEY channel offset, 0 is ch1, 1 is ch2, etc
zTMP2 = $fa	; volume buffer for drawing the screen, also temporary printnote backup
zTMP3 = $fb	; "does AUDCTL have the Poly9 bit?" backup between loops
zTMP4 = $fc	; AUDCTL backup between loops
zTMP5 = $fd	; "does AUDCTL have the 15khz bit?" backup between loops
zINDEX = $fe	; Channel number index, useful for Stereo POKEY
VDSLST = $200	; Vector to Display List Interrupt (DLI) routine
VVBLKI = $222	; Vertical Blank Immediate (VBI) register
KEY = $2fc	; internal hardware value for the last key pressed
MODUL = $4000	; address of RMT module, hardcoded to the .rmt file itself
pm = $a800	; player
mis = $a980	; missile
scr = $aa00	; screen
SETVBV = $e45c	; set system timers during the VBLANK routine
FONT = $bc00	; custom font location
VISDATA = $9000	; all the data like text strings, lookup tables for notes, etc

;*******************************************************************;
;* begin code for the visual player                                *;
;* initialisation and clear memory before executing the next parts *;
;*******************************************************************;

	.include "hw.s"	; a8 hardware registers
	.include "rmtplayr.s"	; include RMT player routines

	ORG	$8000	; RMT Visualizer address, this leaves 16k for the RMT module, should be plenty for most cases
start = *
	; mwa #dlist rDLISTL	; Display Lists address
	lda	#<(dlist)
	sta	rDLISTL
	lda	#>(dlist)
	sta	rDLISTL+1
	;mva rRANDOM v_colour1              ; random colours, used during VBI, RASTERMUSICTRACKER, LOOP, etc
	;mva rRANDOM v_colour2
	;mva rRANDOM v_colour3
	jsr	rmt_silence	; flush all POKEY registers in case leftover data is present

; make all old_ bytes non-zero to force drawing the screen at least once

start_flush = *
	lda	#1	; #1 works fine since #$FF is the note off flag, and volume display could break with other values
	ldx	#0	; set index x to 0
.if STEREOMODE=1	; if stereo mode is set to 1...
	ldy	#41	; ...set index y to #41 for the buffer
.else	; else...
	ldy	#23	; ...set index y to #23 for the buffer
.endif	; endif
flushloop = *
	; write the value in memory, increment index x
	sta	old_memory,x
	inx
	dey	; decremenet the buffer
	bne	flushloop	; repeat until all values are written
	ldx	#$FF	; will be useful for the next part

; startloop is a pretty cheap screen effect with a simple text display
; that whole loop is a big noob-tier level of programming but it works lol

start_loop = *
	ldy	#4	; index y is 4, the loop runs once every 4 frames
start_loop2 = *
	jsr	wait_for_vblank	; wait for vblank, a simple subroutine but works
	; mwa #dlist rDLISTL	; for some reason, the display list address must be loaded each frame, or garbage is output...
	lda	#<(dlist)
	sta	rDLISTL
	lda	#>(dlist)
	sta	rDLISTL+1
        ;mva v_colour2 rCOLBK
	; mva #0 rCOLBK	; black background colour, must also be written each frame for some reason, most likely related to DLIST...
	lda	#0
	sta	rCOLBK
start_loop3 = *
	stx	rCOLPF2	; the value from index x is written in the playfield colour 2 register for a simple fadeing effect
	dey	; decrement index y, once per frame
	bne	start_loop2	; return to the wait for vblank part if index y is not 0
	txa	; copy the value of index x to the accumulator
	; sub #$11	; substract #$11 from it
	sec
	sbc	#$11
	tax	; overwrite the value held in index x
	cpx	#0	; is the value of index x 0?
	bne	start_loop	; nope, start executing the loop again
start_loop4 = *
	jsr	wait_for_vblank	; start of the second subloop, start with a wait for vblank
	; mwa #dlist rDLISTL	; load the display list address again, for the reason mentioned above
	lda	#<(dlist)
	sta	rDLISTL
	lda	#>(dlist)
	sta	rDLISTL+1
	; mva #>FONT rCHBASE	; load the font address into the character register, same things apply to it
	lda	#>FONT
	sta	rCHBASE
        ;mva v_colour2 rCOLBK
	; mva #0 rCOLBK	; load the colour black, then write in the background colour register
	lda	#0
	sta	rCOLBK
	sta	rCOLPF2	; as well as the playfield colour 2 register
	; mva #15 rCOLPF1	; write the value 15 (or $0F), white colour, into the playfield colour register 1
	lda	#15
	sta	rCOLPF1
	cpy	#40	; is the value of index y 40?
	beq	start_loop5	; yes, skip ahead, so no more than 40 characters are drawn on the screen
	; mva txt_start,y scr,y	; draw the text from txt_start, index y is used for the position on screen, the pointer to the text, and the number of characters left
	lda	txt_start,y
	sta	scr,y
	iny	; once the above is done, increment index y
start_loop5 = *
	inx	; increment index x. Both indexes x and y were 0 before this subloop started
	cpx	#120	; is the value of index x 120?
	bne	start_loop4	; nope, start this subloop again. This lasts ~2 seconds in real time

; load the RMT module

start_rmt = *
	; mwa #dlist rDLISTL	; load the display list address again to not display garbage for 1 frame
	lda	#<(dlist)
	sta	rDLISTL
	lda	#>(dlist)
	sta	rDLISTL+1
	ldx	#<MODUL	; low byte of RMT module to index x
	ldy	#>MODUL	; high byte of RMT module to index y
	lda	#STARTLINE	; starting song line 0-255 to the accumulator
	jsr	rmt_init	; initialise the player routines
	tay	; initialisation returns instrument speed (1..4 => from 1/screen to 4/screen), transfer to index y
screen_init = *
	; mva tabpp-1,y acpapx2	; sync counter spacing
	lda	tabpp-1,y
	sta	acpapx2
	; mva #255 KEY	; no key pressed
	lda	#255
	sta	KEY
	; mva #>pm rPMBASE	; player/missile base address
	lda	#>pm
	sta	rPMBASE
	; mva #$26 rDMACTL	; enable missile and dlist dma, normal playfield, double line player
	lda	#$26
	sta	rDMACTL
	; mva #>FONT rCHBASE	; load the font in memory for the last time
	lda	#>FONT
	sta	rCHBASE
	; mva #1 rPRIOR	; all players above playfield
	lda	#1
	sta	rPRIOR
	sta	rGRACTL	; and turn on missiles
	; mva #0 rNMIEN	; write to NMI enable register (disable)
	lda	#0
	sta	rNMIEN
	sta	rCOLBK	; also write the colour black to background colour register
	sta	rCOLPF2	; and to the playfield colour register 2
	;mva v_colour2 rCOLBK
	; mva #$0F rCOLPF1	; colour white written to the playfield colour register 1 for characters on screen
	lda	#$0F
	sta	rCOLPF1
	ldx	#$6C	; funny gradient purple colours on missiles, from brighter to darker
	stx	rCOLPM0	; write the value of index x in missile colour register 0
	; :2 dex	; decrement index x twice
	.repeat 2, I
	dex
	.endrep
	stx	rCOLPM1	; write again to the next missile, and so on
	; :2 dex
	.repeat 2, I
	dex
	.endrep
	stx	rCOLPM2
	; :2 dex
	.repeat 2, I
	dex
	.endrep
	stx	rCOLPM3

; check for the machine region, for setting up playback speed and timer values

region_check = *
	ldy	#156	; stable, default value, any region
	ldx	#4	; 4 characters
	lda	rPAL	; this register defines if PAL or NTSC hardware is used
	and	#14	; NTSC returns 14 (E), PAL returns 0
	pha	; quick push in stack for the next step
.if REGIONPLAYBACK=0	; if the player region defined for PAL...
	; seq:ldy #130	; ...and NTSC is detected, adjust the speed from PAL to NTSC
	beq	:+
	ldy	#130
:
.elseif REGIONPLAYBACK=1	; else, if the player region defined for NTSC...
	; sne:ldy #187	; ...and PAL is detected, adjust the speed from NTSC to PAL
	bne	:+
	ldy	#187
:
.endif	; endif
	pla	; pull the accumulator from stack
	beq	region_is_pal	; zero flag still set from the previous AND operation
	; mva:rne txt_NTSC-1,x scr-1,x-	; display 'NTSC' on the top left corner
:
	lda	txt_NTSC-1,x
	sta	scr-1,x
	dex
	bne	:-
	ldx	#60	; 60 frames per second
	bne	region_done	; not zero, skip to the next part
region_is_pal = *
	; mva:rne txt_PAL-1,x scr-1,x-	; display 'PAL' on the top left corner
:
	lda	txt_PAL-1,x
	sta	scr-1,x
	dex
	bne	:-
	ldx	#50	; 50 frames per second
region_done = *
	stx	v_region	; framerate used for the song timer
	sty	ppap	; value used for screen synchronisation

; graphical elements are now being loaded, includes most text strings and graphic tiles used for displaying a lot of information during playback

graphic_infos = *
	; mva #$1A scr+37	; display ':' for the timer, may be nice to be more than that... like blinking every second...
	lda	#$1A
	sta	scr+37
	ldx	#$54	; the following is a mess... but saves many bytes over the older 'lda, sta' blocks
	stx	scr+77	; display all the graphic tiles for parts like AUDCTL, ORDER, ROW, etc
	inx	; todo: describe these with more clarity, but for now, it just works lol
	stx	scr+78
	inx
	stx	scr+79
	inx
	stx	scr+158
	inx
	stx	scr+159
	inx
	stx	scr+317
	inx
	stx	scr+318
	inx
	stx	scr+319
	stx	scr+399
	inx
	stx	scr+237
	stx	scr+397
	inx
	stx	scr+398
	; :2 inx
	.repeat 2, I
	inx
	.endrep
	stx	scr+238
	inx
	stx	scr+239
.if STEREOMODE=1	; 2nd POKEY, display an extra AUDCTL and SKCTL block at the bottom right
	ldx	#$59
	stx	scr+797
	inx
	stx	scr+798
	inx
	stx	scr+799
	stx	scr+879
	inx
	stx	scr+877
	inx
	stx	scr+878
.endif

; text strings, for song title, credits, etc

song_title = *
	ldx	#29	; 29 characters
	; mva:rne txt_top-1,x scr+4,x-	; display the song title between the region and timer
:
	lda	txt_top-1,x
	sta	scr+4,x
	dex
	bne	:-
stereomode_info = *
	ldx	#40	; 40 characters
	; mva:rne txt_center-1,x scr+480,x-	; Mono or Stereo modes information in the middle of the screen, could also be other stuff if wanted
:
	lda	txt_center-1,x
	sta	scr+480,x
	dex
	bne	:-
credits_info = *
	ldx	#40	; 40 characters
	; mva:rne txt_bot-1,x scr+959,x-	; credits and version at the bottom of the screen
:
	lda	txt_bot-1,x
	sta	scr+959,x
	dex
	bne	:-

; loop for displaying a bunch of repeated elements every few lines for each audio channel

l0 = *
	; mwa #scr zTMP0	; initialise the screen position for the next part	
	lda	#<(scr)
	sta	zTMP0
	lda	#>(scr)
	sta	zTMP0+1
l1 = *
	ldy	#40	; index y will be used for the screen position relative to the offset (zTMP0) here
	; mva #"C"-$20 (zTMP0),y+	; draw character 'C', increment index y
	lda	#$43-$20
	sta	(zTMP0),y
	iny
	; mva #"H"-$20 (zTMP0),y+	; draw character 'H', increment index y
	lda	#$48-$20
	sta	(zTMP0),y
	iny
.if STEREOMODE<>1	; if not Stereo mode 1...
	; mva txt_chs,x+ (zTMP0),y+	; ...draw channel 1,2,3,4, by incrementing index x and y for character and position
	lda	txt_chs,x
	sta	(zTMP0),y
	inx
	iny
	inx	; skip the 'L/R' character by incrementing x again
.else	; else...
	; :2 mva txt_chs,x+ (zTMP0),y+	; run this line twice in a row, once for the channel number then the side (L/R)
	.repeat 2, I
	lda	txt_chs,x
	sta	(zTMP0),y
	inx
	iny
	.endrep
.endif	; endif
l1_a = *
	ldy	#57	; screen position relative to the offset (zTMP0)
	lda	#$3C-$20	; character to draw, here it's '<'
	sta	(zTMP0),y	; draw it to the screen position relative to the offset with index y
	ldy	#97	; next position
	sta	(zTMP0),y	; draw it again there
	ldy	#73	; next position
	lda	#$3E-$20	; character to draw, here it's '>'	
	sta	(zTMP0),y	; draw it there	
	ldy	#113	; next position
	sta	(zTMP0),y	; draw it again there	
l1_b = *
	lda	zTMP0	; load the nexy screen offset position to the accumulator
	; add #120	; skip 3 lines on the screen, 40 character per line, by adding 120 to it
	clc
	adc	#120
	sta	zTMP0	; store the new offset in the zTMP0 variable again
	; scc:inc zTMP0+1	; skip this line on carry clear, or increment the high byte on carry set
	bcc	:+
	inc	zTMP0+1
:
l1_c = *
.if STEREOMODE<>1	; if not Stereo mode 1...
	cpx	#8	; ...compare index x to 8, for 4 channels
.else	; else...
	cpx	#16	; ...compare index x to 16, for 8 channels
.endif	; endif
	bne	l1	; continue drawing the screen elements until x is the wanted value

; initialise the missile position and appearance on the screen

l2 = *
	lda	#1	; different values affect in strange ways, but 1 makes the missiles 1 pixel wide
	ldx	#$12	; vertical position on screen
	ldy	#4	; 4 missiles
l2_a = *
	; :4 sta mis+#,x	; left channels
	.repeat 4, I
	sta	mis+I,x
	.endrep
.if STEREOMODE=1
	; :4 sta mis+48+#,x	; right channels
	.repeat 4, I
	sta	mis+48+I,x
	.endrep
.endif
	; :2 asl @	; move to the correct lines
	.repeat 2, I
	asl	a
	.endrep
l2_b = *
	pha	; push in the stack temporarily
	txa	; copy index x to the accumulator
	adc	#12	; add the space between each missile (in pixels)
	tax	; overwrite index x with the new value
	pla	; pull the backup from the stack to the accumulator
	dey	; decrement index y
	bne	l2_a	; keep going until all missiles have been initialised with the parameters above

;******************************************************;
;* main code loop, everything has been initialised    *;
;* execution will continue from this block infinitely *;
;******************************************************;

mainloop = *
	; mwa VVBLKI oldvbi	; backup the old vbi address (could it be moved elsewhere if startloop uses it own?)
	lda	VVBLKI
	sta	oldvbi
	lda	VVBLKI+1
	sta	oldvbi+1
	; mwa #vbi VVBLKI	; write our own vbi address to it
	lda	#<(vbi)
	sta	VVBLKI
	lda	#>(vbi)
	sta	VVBLKI+1
.if STEREOMODE=1
	; mwa #dli VDSLST	; write our own dli address to the dli vector
	lda	#<(dli)
	sta	VDSLST
	lda	#>(dli)
	sta	VDSLST+1
	; mva #$c0 rNMIEN	; enable vbi and dli interrupts
	lda	#$c0
	sta	rNMIEN
.else
	; mva #$40 rNMIEN	; enable vbi interrupts
	lda	#$40
	sta	rNMIEN
.endif

; loop running every frame between vbi and player calls... couldn't figure it out yet but it does its thing like expected :D

loop = *
	lda	spap
	ldx	#0
cku = *-1
	bne	keepup
	lda	rVCOUNT	; vertical line counter synchro
	tax
	; sub #VLINE
	sec
	sbc	#VLINE
lastpap = *-1
	; scs:adc #$ff
	bcs	:+
	adc	#$ff
:
ppap = *-1
	sta	dpap
	stx	lastpap
	lda	#0
spap = *-1
	; sub #0
	sec
	sbc	#0
dpap = *-1
	sta	spap
	bcs	loop
keepup = *
	adc	#$ff
acpapx2 = *-1
	sta	spap
	ldx	#0
	; scs:inx
	bcs	:+
	inx
:
	stx	cku

; change the colour for the rasterbar, and run the player routines

play_loop = *
	;mva v_colour1 rCOLBK            ; random colour 1 for rasterbar
	lda	#$69	; a nice purpleish pink
	sta	rWSYNC	; wait for horizontal sync
	sta	rCOLBK	; background colour
	jsr	rmt_play	; setpokey then 1 play

; songline position (pattern order) for the display and the timer, as the player computes it for the Simple RMT Player:
; (ptrSongLines - song start) / TRACKS, minus 1 because after rmt_play ptrSongLines points to the next songline

	lda	ptrSongLines
	; sub MODUL+14
	sec
	sbc	MODUL+14
	sta	v_ord
	lda	ptrSongLines+1
	sbc	MODUL+15
	lsr	a
	ror	v_ord
	lsr	a
	ror	v_ord
.if TRACKS>4
	lsr	a
	ror	v_ord
.endif
	dec	v_ord
	;mva v_colour2 rCOLBK            ; random colour 2 for background
	lda	#0	; black colour
	sta	rWSYNC	; wait for horizontal sync
	sta	rCOLBK	; background colour

; check for keyboard input

	lda	KEY	; keyboard
	cmp	#28	; ESCape key?
	bne	loop	; no => loop

; stop music and exit to DOS (or Self Test by default)

stopmusic = *
	; mva #255 KEY	; no key pressed
	lda	#255
	sta	KEY
	jsr	rmt_silence	; all sounds off
	; mva #0 rNMIEN	; disable interrupts
	lda	#0
	sta	rNMIEN
	sta	rGRACTL	; turn off players and missiles
	; :4 sta rHPOSM0+#	; reset missiles position
	.repeat 4, I
	sta	rHPOSM0+I
	.endrep
	; mwa oldvbi VVBLKI	; restore the old vbi address
	lda	oldvbi
	sta	VVBLKI
	lda	oldvbi+1
	sta	VVBLKI+1
	; mva #$40 rNMIEN	; enable vbi interrupts
	lda	#$40
	sta	rNMIEN
	jmp	(10)	; DOSVEC => exit to DOS

;************************************************************;
;* begin vbi routines                                       *;
;* most of the information to display on screen starts here *;
;************************************************************;

vbi = *
        ;mva v_colour3 rCOLBK            ; funny rasterbar, during (extended) vbi
	; mva #$9F rCOLBK	; debug colour
	lda	#$9F
	sta	rCOLBK
	; :4 mva mistmp+# rHPOSM0+#	; update missiles
	.repeat 4, I
	lda	mistmp+I
	sta	rHPOSM0+I
	.endrep
	; mwa #dlist rDLISTL	; update display list
	lda	#<(dlist)
	sta	rDLISTL
	lda	#>(dlist)
	sta	rDLISTL+1
	jsr	timecounterstart	; update the time counter
	jsr	clear_volume	; clear the volume bars when needed

; VERY lazy tiles clear, temporary setup, stereo is not yet supported...

clear_tiles_1 = *
	ldx	#0
	ldy	v_audctl
	cpy	old_audctl
	beq	clear_tiles_2	; skip hpf clear
clear_hpf_check_13 = *
        ;tya
        ;and #4 ; hpf 1+3
        ;beq clear_hpf_tiles_13
clear_hpf_check_24 = *
        ;tya
        ;and #2 ; hpf 2+4
        ;beq clear_hpf_tiles_24
        ;jmp clear_tiles_2

clear_hpf_tiles_13 = *

	;ldx #17 ; 1
	stx	scr+114
	stx	scr+115
	stx	scr+155
	stx	scr+195
	stx	scr+235
	stx	scr+275
	stx	scr+315
	stx	scr+354
	stx	scr+355
	;jmp clear_hpf_check_24

clear_hpf_tiles_24 = *
	;ldx #18 ; 2
	stx	scr+234
	stx	scr+235
	stx	scr+236
	stx	scr+276
	stx	scr+316
	stx	scr+356
	stx	scr+396
	stx	scr+436
	stx	scr+474
	stx	scr+475
	stx	scr+476

clear_tiles_2 = *
	;mwa #scr+97 clrt                ; clear the channel join junk from the 4 first channels
	;jsr clrft                       ; screw this subroutine, never again LOL
	;IFT STEREOMODE==1               ; 8 channels total, so the second half of the screen is cleared too
	;mwa #scr+577 clrt
	;jsr clrft
	;EIF

	; mva #$98 rCOLBK	; debug colour
	lda	#$98
	sta	rCOLBK

; print time (minutes:seconds)

print_minute = *
	ldy	v_minute
	cpy	old_minute
	beq	print_second
	sty	old_minute
	; mwa #scr+35 zARG0
	lda	#<(scr+35)
	sta	zARG0
	lda	#>(scr+35)
	sta	zARG0+1
	tya
	jsr	printhex

print_second = *
	ldy	v_second
	cpy	old_second
	beq	print_order
	sty	old_second
	; mwa #scr+38 zARG0
	lda	#<(scr+38)
	sta	zARG0
	lda	#>(scr+38)
	sta	zARG0+1
	tya
	jsr	printhex

; print pattern order and row

print_order = *
	ldy	v_ord
	cpy	old_ord
	beq	print_row
	sty	old_ord
	; mwa #scr+118 zARG0
	lda	#<(scr+118)
	sta	zARG0
	lda	#>(scr+118)
	sta	zARG0+1
	tya
	jsr	printhex

print_row = *
	ldy	smc_abeat
	cpy	old_abeat
	beq	print_speed
	sty	old_abeat
	; mwa #scr+198 zARG0
	lda	#<(scr+198)
	sta	zARG0
	lda	#>(scr+198)
	sta	zARG0+1
	tya
	jsr	printhex

; print SPEED

print_speed = *
	ldy	smc_speed
	cpy	old_speed
	beq	print_skctl
	sty	old_speed
	; mwa #scr+278 zARG0
	lda	#<(scr+278)
	sta	zARG0
	lda	#>(scr+278)
	sta	zARG0+1
	tya
	jsr	printhex

; print SKCTL

print_skctl = *
	ldy	v_skctl
	cpy	old_skctl
	beq	print_skctl2
	sty	old_skctl
	; mwa #scr+438 zARG0
	lda	#<(scr+438)
	sta	zARG0
	lda	#>(scr+438)
	sta	zARG0+1
	tya
	jsr	printhex
	lda	v_skctl
	cmp	#$8B
	bne	print_skctl2
	; mwa #scr+80 zARG0
	lda	#<(scr+80)
	sta	zARG0
	lda	#>(scr+80)
	sta	zARG0+1
	jsr	print_joined_2T

print_skctl2 = *
.if STEREOMODE=1
	ldy	v_skctl2
	cpy	old_skctl2
	beq	print_audctl
	sty	old_skctl2
	; mwa #scr+918 zARG0
	lda	#<(scr+918)
	sta	zARG0
	lda	#>(scr+918)
	sta	zARG0+1
	tya
	jsr	printhex
	lda	v_skctl2
	cmp	#$8B
	bne	print_audctl
	; mwa #scr+560 zARG0
	lda	#<(scr+560)
	sta	zARG0
	lda	#>(scr+560)
	sta	zARG0+1
	jsr	print_joined_2T
.endif

; print AUDCTL and filter tiles

print_audctl = *
	ldy	v_audctl
	cpy	old_audctl
	beq	print_filter
	; mwa #scr+358 zARG0
	lda	#<(scr+358)
	sta	zARG0
	lda	#>(scr+358)
	sta	zARG0+1
	tya
	jsr	printhex
	lda	v_audctl
	jmp	print_filter_a
print_filter = *
	tya
print_filter_a = *
	and	#4	; highpass 1+3
	beq	print_filter_b	; nope
	; mwa #scr zARG0
	lda	#<(scr)
	sta	zARG0
	lda	#>(scr)
	sta	zARG0+1
	; mwa #scr+240 zARG1
	lda	#<(scr+240)
	sta	zARG1
	lda	#>(scr+240)
	sta	zARG1+1
	jsr	printhpf_13
	lda	v_audctl
	jmp	print_filter_c
print_filter_b = *
	tya
print_filter_c = *
	and	#2	; highpass 2+4
	beq	print_audctl2	; nope
	; mwa #scr zARG0
	lda	#<(scr)
	sta	zARG0
	lda	#>(scr)
	sta	zARG0+1
	; mwa #scr+240 zARG1
	lda	#<(scr+240)
	sta	zARG1
	lda	#>(scr+240)
	sta	zARG1+1
	jsr	printhpf_24

print_audctl2 = *
.if STEREOMODE=1
	ldy	v_audctl2
	cpy	old_audctl2
	beq	print_filter2
	; mwa #scr+838 zARG0
	lda	#<(scr+838)
	sta	zARG0
	lda	#>(scr+838)
	sta	zARG0+1
	tya
	jsr	printhex
	lda	v_audctl2
	jmp	print_filter2_a
print_filter2 = *
	tya
print_filter2_a = *
	and	#4	; highpass 1+3
	beq	print_filter2_b	; nope
	; mwa #scr+480 zARG0
	lda	#<(scr+480)
	sta	zARG0
	lda	#>(scr+480)
	sta	zARG0+1
	; mwa #scr+720 zARG1
	lda	#<(scr+720)
	sta	zARG1
	lda	#>(scr+720)
	sta	zARG1+1
	jsr	printhpf_13
	lda	v_audctl2
	jmp	print_filter2_c
print_filter2_b = *
	tya
print_filter2_c = *
	and	#2	; highpass 2+4
	beq	print_ch_infos	; nope
	; mwa #scr+480 zARG0
	lda	#<(scr+480)
	sta	zARG0
	lda	#>(scr+480)
	sta	zARG0+1
	; mwa #scr+720 zARG1
	lda	#<(scr+720)
	sta	zARG1
	lda	#>(scr+720)
	sta	zARG1+1
	jsr	printhpf_24
.endif

; print channel infos

print_ch_infos = *
	ldx	#0	; index x equals channel 1
	stx	zINDEX	; channel number per POKEY chip
	stx	zTMP1	; zTMP1 is the variable holding the value of index temporarily during the loop
vbil1 = *
	lda	infoposLo,x
	sta	zARG0
	lda	infoposHi,x
	sta	zARG0+1
vbil1_a = *
	cpx	#0	; x could NOT be 0 since a loop was executed at least once
	bne	vbil2_a	; if index x is not 0, skip the entire AUDCTL block below, it's only done once per variable that way
vbil1_b = *
	lda	v_audctl	; start by loading the current v_audctl value
	sta	zTMP4	; audctl backup for the next parts, this way each POKEY can efficiently rely on the same code
	cmp	old_audctl	; compare with the old one in memory
	beq	print_audf_a	; if they are the same value, skip the entire AUDCTL stuff, the same values used before will remain displayed on screen	
vbil2 = *
	and	#1	; 15kHz mode   ; if this came from the end of vbis3, v_audctl2 is written in memory and continue the same was as before
	; :2 asl @	; x4
	.repeat 2, I
	asl	a
	.endrep
	sta	zTMP5
	lda	zTMP4
	ldy	#0
	and	#$80	; 9-bit poly
	; seq:ldy #$40	; offset the pointer for Poly9 text
	beq	:+
	ldy	#$40
:
	sty	zTMP3
vbil2_a = *
	ldy	zTMP5
	lda	zTMP4
	and	ctlcmp,x
	; seq:ldy ctlval,x
	beq	:+
	ldy	ctlval,x
:
	tya
	tax
vbil2_b = *
	cpx	#12
	bne	vbil2_c	; not 16-bit, move to the remaining part
	lda	zARG0
	pha
	; sub #80	; set the correct position on the screen
	sec
	sbc	#80
	sta	zARG0	; a cursed workaround, better than the older method
	jsr	print_joined_16
	pla
	sta	zARG0
vbil2_c = *
	ldy	#40	; position on screen
	; mva #5 zTMP0	; 5 characters
	lda	#5
	sta	zTMP0
	txa
	asl	a	; make the index 8 bytes long
	tax
print_vbil2_c = *
	; mva txt_clock,x+ (zARG0),y+
	lda	txt_clock,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	print_vbil2_c

; print AUDF

print_audf = *
	ldx	zTMP1
print_audf_a = *
	lda	trackn_audf,x
	cmp	old_audf,x
	beq	print_audc_a
	ldy	#12
	jsr	printhex_direct

; print AUDC

print_audc = *
	ldx	zTMP1
print_audc_a = *
	lda	trackn_audc,x
	cmp	old_audc,x
	beq	printnote_check_volume
	ldy	#14
	jsr	printhex_direct

printnote_checks = *

.if DISPLAYNOTES=1

; a bunch of hack code to display notes with questionable accuracy

	ldx	zTMP1	; channel index currently in use
printnote_check_volume = *
	lda	trackn_audc,x	; AUDC value of the channel identified by x 
	tay	; backup the value for the first check
	and	#$0F	; clear the distortion bits
	bne	printnote_check_volume_c	; not volume 0, continue like normal
	lda	#$FF	; 'note was off at least once' flag
	cmp	old_off,x	; was it off just before?      
	bne	printnote_check_volume_b	; was not, continue
	jmp	print_other	; skip the entire print_note block otherwise
printnote_check_volume_b = *
	sta	old_off,x	; set the flag
	jmp	printnote_off	; volume 0, finish this block by printing 'off'
printnote_check_volume_c = *
	sta	old_off,x	; reset the flag, it will never be #$FF here so anything works

printnote_check_noise = *
	tya	; get the AUDC value back to accumulator
	and	#$E0	; clear most of the unecessary information
	cmp	#$80	; distortion 8
	; jeq printnote_noise
	bne	:+
	jmp	printnote_noise
:
	cmp	#$00	; distortion 0
	; jeq printnote_noise
	bne	:+
	jmp	printnote_noise
:
	sta	zTMP2	; temporary backup for later parts

printnote_check_channel_number = *
	ldy	zTMP4	; audctl backup made earlier
	lda	zINDEX	; channel number
	cmp	#0
	beq	printnote_check_179mhz_ch1
	cmp	#1
	beq	printnote_check_join_ch2
	cmp	#2
	beq	printnote_check_179mhz_ch3
	cmp	#3
	beq	printnote_check_join_ch4
	jmp	printnote_fallback	; failsafe     
printnote_check_audctl = *

printnote_check_179mhz_ch1 = *
	tya
	and	#$40	; 1.79mhz ch1
	beq	printnote_check_15khz
	bne	printnote_179mhz
printnote_check_179mhz_ch3 = *
	tya
	and	#$20	; 1.79mhz ch3
	beq	printnote_check_15khz
	bne	printnote_179mhz
printnote_check_join_ch2 = *
	tya
	and	#$10	; Join 1+2
	beq	printnote_check_15khz
	jmp	printnote_fallback
printnote_check_join_ch4 = *
	tya
	and	#$08	; Join 3+4
	beq	printnote_check_15khz
	jmp	printnote_fallback
printnote_check_15khz = *
	tya
	and	#$01
	beq	printnote_64khz

printnote_15khz = *
	lda	zTMP2	; distortion backup
	cmp	#$A0	; distortion A
	beq	printnote_dist_a_15khz
	jmp	printnote_fallback	; failsafe   

printnote_179mhz = *
	lda	zTMP2	; distortion backup
	cmp	#$20	; distortion 2
	beq	printnote_dist_2_179mhz
	jmp	printnote_fallback	; failsafe  

printnote_64khz = *
	lda	zTMP2	; distortion backup
	cmp	#$C0	; distortion C
	beq	printnote_dist_c_64khz
	cmp	#$A0	; distortion A
	beq	printnote_dist_a_64khz
	jmp	printnote_fallback	; failsafe 

printnote_dist_a_64khz = *
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen        
	lda	trackn_audf,x	; frequency of the channel, 256 possible values
	tax	; the value becomes the new index x
	lda	txt_dist_a_64khz_freqs,x	; seek for the note referenced by the previous table
	bmi	printnote_dist_a_15khz_a	; seek for alternative notes if needed
	; :2 asl @	; shift right twice, so index entries are 4 bytes long 
	.repeat 2, I
	asl	a
	.endrep
	tax	; transfer to index x, will be used for looking up what musical note will be displayed on screen

printnote_oct3 = *
	; mva txt_notes_oct3,x+ (zARG0),y+
	lda	txt_notes_oct3,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct3
	jmp	print_other
printnote_dist_a_64khz_a = *
	ldx	#0
printnote_oct3_minus_4 = *
	; mva txt_notes_oct3-4,x+ (zARG0),y+
	lda	txt_notes_oct3-4,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct3_minus_4
	jmp	print_other

printnote_dist_c_64khz = *
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen  
	lda	trackn_audf,x	; frequency of the channel, 256 possible values
	tax	; the value becomes the new index x
	lda	txt_dist_c_64khz_freqs,x	; seek for the note referenced by the previous table
	; :2 asl @	; shift right twice, so index entries are 4 bytes long 
	.repeat 2, I
	asl	a
	.endrep
	tax	; transfer to index x, will be used for looking up what musical note will be displayed on screen

printnote_oct0 = *
	; mva txt_notes_oct0,x+ (zARG0),y+
	lda	txt_notes_oct0,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct0
	jmp	print_other

printnote_dist_2_179mhz = *
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen 
	lda	trackn_audf,x
	tax
	lda	txt_dist_2_179mhz_freqs,x
	; :2 asl @	; shift right twice, so index entries are 4 bytes long 
	.repeat 2, I
	asl	a
	.endrep
	tax	; transfer to index x, will be used for looking up what musical note will be displayed on screen
	jmp	printnote_oct3

printnote_dist_a_15khz = *
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen        
	lda	trackn_audf,x	; frequency of the channel, 256 possible values
	tax	; the value becomes the new index x
	lda	txt_dist_a_15khz_freqs,x	; seek for the note referenced by the previous table
	bmi	printnote_dist_a_15khz_a	; seek for alternative notes if needed
	; :2 asl @	; shift right twice, so index entries are 4 bytes long 
	.repeat 2, I
	asl	a
	.endrep
	tax	; transfer to index x, will be used for looking up what musical note will be displayed on screen

printnote_oct1 = *
	; mva txt_notes_oct1,x+ (zARG0),y+
	lda	txt_notes_oct1,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct1
	jmp	print_other
printnote_dist_a_15khz_a = *
	ldx	#0
printnote_oct1_minus_4 = *
	; mva txt_notes_oct1-4,x+ (zARG0),y+
	lda	txt_notes_oct1-4,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct1_minus_4
	jmp	print_other

printnote_noise = *	; display "Noise" when called
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen       
	ldx	#0	; failsafe, since only 1 outcome is possible, this is to avoid garbage being read	
printnote_noise_a = *
	; mva txt_notes_noise,x+ (zARG0),y+
	lda	txt_notes_noise,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_noise_a
	jmp	print_other

printnote_off = *	; display "Off" when called
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen       
	ldx	#0	; failsafe, since only 1 outcome is possible, this is to avoid garbage being read	        
printnote_off_a = *
	; mva txt_notes_off,x+ (zARG0),y+
	lda	txt_notes_off,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_off_a
	jmp	print_other

printnote_fallback = *	; else, fallback to the original approach using 'trackn_note' values
	; mva #4 zTMP0	; 4 characters to display
	lda	#4
	sta	zTMP0
	ldy	#6	; position on the screen       
	lda	trackn_note,x	; this variable is the note visually output in the tracker itself
	; :2 asl @	; shift right twice, so index entries are 4 bytes long 
	.repeat 2, I
	asl	a
	.endrep
	tax	; transfer to index x, will be used for looking up what musical note will be displayed on screen
	;jmp printnote_oct1                     ; by default RMT starts on octave 1, so this is visually matching

printnote_oct4 = *
	; mva txt_notes_oct4,x+ (zARG0),y+
	lda	txt_notes_oct4,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printnote_oct4

.endif

; print other infos like poly or clock

print_other = *
	ldx	zTMP1
	lda	trackn_audc,x
	cmp	old_audc,x
	beq	vbis1_b
	tay
	ldx	#16*4
	and	#$10	; vol only
	bne	vbis1
	tya
	and	#$e0
	; :2 lsr @	; x2 for indexes of 8 bytes each
	.repeat 2, I
	lsr	a
	.endrep
	; add zTMP3
	clc
	adc	zTMP3
	tax
vbis1 = *
	ldy	#46
	; mva #6 zTMP0	; 6 characters
	lda	#6
	sta	zTMP0
print_vbis1 = *
	; mva txt_polys,x+ (zARG0),y+
	lda	txt_polys,x
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	print_vbis1

; print horizontal volume bars

vbis1_a = *
	ldx	zTMP1	; load the index x for the channel offset
	lda	trackn_audc,x	; load the AUDC value of the channel indexed by x
	cmp	old_audc,x	; compare the old AUDC value to the current one
vbis1_b = *
	beq	vbis2	; the same AUDC value is used, skip
	sta	old_audc,x	; save the old AUDC value for the next frame
	and	#$f	; clear the distortion bits
	sta	v_volume,x	; save for the clear screen routine
	beq	vbis2	; volume 0, skip
vbis1_c = *
	; sub old_volume,x	; substract the old volume value to the current one
	sec
	sbc	old_volume,x
	bmi	vbis2	; result is negative, skip
	beq	vbis2	; result is 0, skip
	sta	zTMP2	; save as the volume value buffer
	lda	old_volume,x	; load the old volume value in the accumulator
	; add #58	; add the screen position relative to the offset (zARG0)
	clc
	adc	#58
	tay	; transfer to the index y for the next part
	lda	#$80	; inverted space character
vbil3 = *
	; write a character on screen, increment the screen position
	sta	(zARG0),y
	iny
	dec	zTMP2	; decrement the buffer
	bne	vbil3	; repeat until the buffer is 0, meaning all characters were drawn

; print pitch using missiles position

vbis2 = *
	lda	trackn_audf,x
	cmp	old_audf,x
	beq	vbis2_a	; skip updating the missiles, they will use the same position
	sta	old_audf,x

	eor	#$ff
	; :2 lsr @
	.repeat 2, I
	lsr	a
	.endrep
	; add #$75
	clc
	adc	#$75
	sta	mistmp,x
vbis2_a = *
	inc	zINDEX
	inx
	stx	zTMP1
	cpx	#4

.if STEREOMODE=1
	bne	vbis3
	; mva #0 zINDEX
	lda	#0
	sta	zINDEX
	lda	v_audctl2
	sta	zTMP4
	jmp	vbil2
vbis3 = *
	cpx	#8
.endif

	bne	vbis4
	jmp	vbis4_b
vbis4 = *
	lda	v_audctl
	cmp	old_audctl
	beq	vbis4_a
	jmp	vbil1
vbis4_a = *
	lda	infoposLo,x
	sta	zARG0
	lda	infoposHi,x
	sta	zARG0+1
	jmp	print_audf_a	; skip the AUDCTL stuff 
vbis4_b = *
	; mva v_audctl old_audctl
	lda	v_audctl
	sta	old_audctl
.if STEREOMODE=1
	; mva v_audctl2 old_audctl2
	lda	v_audctl2
	sta	old_audctl2
.endif
vbis4_c = *
	; mva #$64 rCOLBK	; debug colour
	lda	#$64
	sta	rCOLBK
	;mva #0 rCOLBK
	pla
	tay
	pla
	tax
	pla
	rti

; print the high pass filter tiles on the screen

printhpf_13 = *
	ldy	#114
	; mva #$45 (zARG0),y+	; horz line
	lda	#$45
	sta	(zARG0),y
	iny
	; mva #$41 (zARG0),y	; dl corner
	lda	#$41
	sta	(zARG0),y
	lda	#$44	; vert line
	ldy	#155
	sta	(zARG0),y
	ldy	#75
	sta	(zARG1),y
	ldy	#114
	; mva #$45 (zARG1),y+	; horz line
	lda	#$45
	sta	(zARG1),y
	iny
	; mva #$40 (zARG1),y	; ul corner	
	lda	#$40
	sta	(zARG1),y
	ldy	#195
	; mva #$7B (zARG0),y	; H
	lda	#$7B
	sta	(zARG0),y
	ldy	#235
	; mva #$7C (zARG0),y	; P
	lda	#$7C
	sta	(zARG0),y
	ldy	#35
	; mva #$7D (zARG1),y	; F
	lda	#$7D
	sta	(zARG1),y
	rts

printhpf_24 = *
	ldy	#234
	; mva #$45 (zARG0),y+	; horz line
	lda	#$45
	sta	(zARG0),y
	iny
	sta	(zARG0),y
	iny
	; mva #$41 (zARG0),y	; dl corner
	lda	#$41
	sta	(zARG0),y
	ldy	#234
	; mva #$45 (zARG1),y+	; horz line
	lda	#$45
	sta	(zARG1),y
	iny
	sta	(zARG1),y
	iny
	; mva #$40 (zARG1),y	; ul corner
	lda	#$40
	sta	(zARG1),y
	lda	#$44	; vert line
	ldy	#36
	sta	(zARG1),y
	ldy	#196
	sta	(zARG1),y
	ldy	#76
	; mva #$7B (zARG1),y	; H
	lda	#$7B
	sta	(zARG1),y
	ldy	#116
	; mva #$7C (zARG1),y	; P
	lda	#$7C
	sta	(zARG1),y
	ldy	#156
	; mva #$7D (zARG1),y	; F
	lda	#$7D
	sta	(zARG1),y
	rts

; print the 'Join' tiles, used by either 16-bit mode or Two-Tone filter

print_joined_2t = *
	ldy	#74
	; mva #$05 (zARG0),y	; 2
	lda	#$05
	sta	(zARG0),y
	ldy	#114
	; mva #$20 (zARG0),y	; T
	lda	#$20
	sta	(zARG0),y
	bne	print_joined_corners	; not zero, will branch to it every time

print_joined_16 = *
	ldy	#74
	; mva #$3E (zARG0),y	; 1
	lda	#$3E
	sta	(zARG0),y
	ldy	#114
	; mva #$3F (zARG0),y	; 6
	lda	#$3F
	sta	(zARG0),y

print_joined_corners = *
	ldy	#34
	; mva #$41 (zARG0),y	; top right
	lda	#$41
	sta	(zARG0),y
	ldy	#154
	; mva #$40 (zARG0),y	; bottom right
	lda	#$40
	sta	(zARG0),y
	rts

; timer routines, took a bit of work but this works as is, no extra work necessary, call every vblank

timecounterstart = *
	ldx	v_frame	; load the frame count
	ldy	#0	; initialisation of timer, both for checks and reset of timer when needed
	cpy	smc_abeat	; are we on row 0?
	bne	secondcounter	; no, continue counting time
	cpy	v_ord	; are we on pattern order 0? This is assumed to be song start
	beq	timecountereset	; yes, reset the entire timer, else, continue counting time

secondcounter = *
	inx	; increment the frame count by 1, this should happen only once per vblank
	stx	v_frame	; store the frame count in memory
	cpx	v_region	; NTSC or PAL? Either 60 or 50 frames
	bne	timecounternext	; not a second yet, continue
	sty	v_frame	; resets the frame counter to 0, restarting the seconds timer
	sed	; set decimal flag for the seconds and minutes counter
	tya	; since index y has 0 in memory, copy to accumulator
	adc	v_second	; increment the second count by 1, result in the accumulator
	sta	v_second	; store the new value in memory
	cmp	#$60	; we need 60 seconds to form a minute, must be a hex value to work properly!
	bne	timecounternext	; not a minute yet, continue

minutecounter = *
	sty	v_second	; reset the second counter to zero, restarting the minutes timer
	tya	; since index y has 0 in memory, copy to accumulator
	adc	v_minute	; increment the minute count by 1, result in the accumulator.
	sta	v_minute	; store the new value in memory, it will increment infinitely in looped tunes, except on pattern order 0

timecounternext = *
	cld	; clear decimal mode, things break if omitted! 
	rts	; timer subroutine finished

timecountereset = *	; store the values of 0 in all variables to reset them
	sty	v_frame	; 0 frame, 60 of these are needed for 1 second in NTSC, 50 in PAL
	sty	v_second	; 0 second, 60 are needed for a minute
	sty	v_minute	; 0 minute, this one counts up to 99 then overflows back to 0 with the current code
	rts	; since we're now set to 00:00, the timer initialisation is now finished

; print text from data tables, useful for things like Polys, Clocks, Notes, etc

printinfo = *
	lda	$ffff,x
infosrc = *-2
	sta	(zARG0),y
	inx
	iny
	dec	zTMP0
	bne	printinfo
	rts

; print hex characters for several things, useful for displaying all sort of debugging infos

printhex = *
	ldy	#0
printhex_direct = *	; workaround to allow being addressed with y in different subroutines
	pha
	; :4 lsr @
	.repeat 4, I
	lsr	a
	.endrep
	;beq ph1    ; comment out if you want to hide the leftmost zeroes
	tax
	lda	hexchars,x
ph1 = *
	sta	(zARG0),y
	iny
	pla
	and	#$f
	tax
	; mva hexchars,x (zARG0),y
	lda	hexchars,x
	sta	(zARG0),y
	rts
hexchars = *
	.byte	$10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $21, $22, $23, $24, $25, $26	; d"0123456789ABCDEF"

; display list interrupt block

.if STEREOMODE=1
dli = *
	pha
	;mva #$3F rCOLBK    ; debug colour
	; :4 mva mistmp+4+# rHPOSM0+#
	.repeat 4, I
	lda	mistmp+4+I
	sta	rHPOSM0+I
	.endrep
	;mva #$78 rCOLBK    ; debug colour
	pla
	rti
.endif

; wait for vblank subroutine

wait_for_vblank = *
	lda	RTCLOK+2
wait = *
	cmp	RTCLOK+2
	beq	wait
	rts

; clear horizontal volume bars

clear_volume = *
	; mwa #scr zARG0	; set initial screen position
	lda	#<(scr)
	sta	zARG0
	lda	#>(scr)
	sta	zARG0+1
	ldx	#0	; start with channel 1
	beq	clear_volume_start	; go right to the first loop
clear_volume_loop = *
	lda	zARG0	; load the nexy screen offset position to the accumulator
	; add #120	; skip 3 lines on the screen, 40 character per line, by adding 120 to it
	clc
	adc	#120
	sta	zARG0	; store the new offset in the zARG0 variable again
	; scc:inc zARG0+1	; skip this line on carry clear, or increment the high byte on carry set
	bcc	:+
	inc	zARG0+1
:
clear_volume_start = *
	lda	old_volume,x	; load the last channel volume value
	beq	clear_volume_next	; volume 0, nothing to clear
	tay	; temporary backup to index y
	; sub v_volume,x	; substract the current volume value
	sec
	sbc	v_volume,x
	bmi	clear_volume_next	; result is negative, skip
	beq	clear_volume_next	; result is 0, skip
	sta	zTMP2	; save as the volume value buffer
	tya	; reload the old volume value in memory
	; add #97	; add the screen position relative to the offset (zARG0)
	clc
	adc	#97
	tay	; transfer back to index y for the next part
	lda	#0	; space (empty) character
clear_volume_continue = *
	; write a character on screen, decrement the screen position
	sta	(zARG0),y
	dey
	dec	zTMP2	; decrement the buffer
	bne	clear_volume_continue	; repeat until the buffer is 0, meaning all characters were drawn
clear_volume_next = *
	; mva v_volume,x old_volume,x	; reload the current volume value and save it over the old value for the next frame
	lda	v_volume,x
	sta	old_volume,x
	inx	; increment the index x to point the next channel
	cpx	#4	; were all 4 channels done?
	bne	clear_volume_loop	; not yet, redo the same loop with the next channel
	rts	; and done

;******************************************************************************;
;* Most of this part is data used to display text, and some other misc infos. *;
;******************************************************************************;

	ORG	VISDATA

; dumb shit again...

txt_start = *
	.byte	$00, $00, $00, $00, $00, $00, $33, $74, $61, $72, $74, $69, $6E, $67, $00, $32, $2D, $34, $00, $36, $69, $73, $75, $61, $6C, $69, $7A, $65, $72, $0E, $0E, $0E, $00, $00, $00, $00, $00, $00, $00, $00	; d"      Starting RMT Visualizer...        "
       ;dta d"00000FlololololololololololololoF0000000" ; template for 40 characters

; song title, or anything that fits the purpose

txt_top = *
	.byte	$00, $00, $00, $27, $65, $6E, $65, $72, $69, $63, $00, $33, $6F, $6E, $67, $00, $34, $69, $74, $6C, $65, $0E, $6D, $70, $13, $00, $00, $00, $00	; d"   Generic Song Title.mp3    "
       ;dta d"   Generic Song Title.mp3    " ; template for 29 characters

; region text, either one is picked automatically using a simple detection method

txt_NTSC = *
	.byte	$AE, $B4, $B3, $A3	; d"NTSC"*
txt_PAL = *
	.byte	$B0, $A1, $AC	; d"PAL"*
	.byte	$00	; d" "

; some extra text, indicative of what setup is used, or just placeholder text

txt_center = *
.if STEREOMODE=0
	.byte	$00, $00, $2D, $6F, $6E, $6F, $00, $30, $6C, $61, $79, $62, $61, $63, $6B, $0C, $00, $12, $6E, $64, $00, $30, $2F, $2B, $25, $39, $00, $24, $69, $73, $61, $62, $6C, $65, $64, $0E, $00, $00, $00, $00	; d"  Mono Playback, 2nd POKEY Disabled.    "
.elseif STEREOMODE=1
	.byte	$00, $33, $74, $65, $72, $65, $6F, $00, $30, $6C, $61, $79, $62, $61, $63, $6B, $0C, $00, $12, $00, $30, $2F, $2B, $25, $39, $00, $23, $68, $69, $70, $73, $00, $35, $73, $65, $64, $0E, $00, $00, $00	; d" Stereo Playback, 2 POKEY Chips Used.   "
.elseif STEREOMODE=4
	.byte	$24, $75, $61, $6C, $00, $2D, $6F, $6E, $6F, $00, $30, $6C, $61, $79, $62, $61, $63, $6B, $0C, $00, $12, $00, $30, $2F, $2B, $25, $39, $00, $23, $68, $69, $70, $73, $00, $35, $73, $65, $64, $0E, $00	; d"Dual Mono Playback, 2 POKEY Chips Used. "
.else
	.byte	$1D, $1D, $1D, $1D, $1D, $1D, $34, $28, $29, $33, $00, $33, $30, $21, $23, $25, $00, $29, $33, $00, $21, $00, $30, $2C, $21, $23, $25, $28, $2F, $2C, $24, $25, $32, $1D, $1D, $1D, $1D, $1D, $1D, $1D	; d"======THIS SPACE IS A PLACEHOLDER======="	; template for 40 characters
.endif

; text used at the bottom for credits and version info

txt_bot = *
	.byte	$32, $2D, $34, $00, $36, $69, $73, $75, $61, $6C, $69, $7A, $65, $72, $00, $62, $79, $00, $30, $69, $67, $75, $0D, $21, $00, $06, $00, $36, $69, $6E, $73, $23, $6F, $6F, $6C, $00	; d"RMT Visualizer by Pigu-A & VinsCool "
	.byte	$F6, $90, $8E, $97	; d"v0.7"*
       ;dta d"00000FlololololololololololololoF0000000" ; template for 40 characters

; text strings used for channel number and side when necessary

txt_chs = *
	.byte	$11	; d"1"
	.byte	$AC	; d"L"*
	.byte	$12	; d"2"
	.byte	$AC	; d"L"*
	.byte	$13	; d"3"
	.byte	$AC	; d"L"*
	.byte	$14	; d"4"
	.byte	$AC	; d"L"*
	.byte	$11	; d"1"
	.byte	$B2	; d"R"*
	.byte	$12	; d"2"
	.byte	$B2	; d"R"*
	.byte	$13	; d"3"
	.byte	$B2	; d"R"*
	.byte	$14	; d"4"
	.byte	$B2	; d"R"*

; POKEY clock, and 16-bit text strings

txt_clock = *
	.byte	$16, $14, $48, $49, $00, $00, $00, $00	; 64khz
	.byte	$11, $15, $48, $49, $00, $00, $00, $00	; 15khz
	.byte	$11, $4A, $19, $47, $49, $00, $00, $00	; 1.79mhz
	.byte	$11, $16, $4B, $4C, $74, $00, $00, $00	; 16-bit

; POKEY distortions (Poly), could be a little less ambiguous sometime later

txt_polys = *	; distortion 0, 2, 4... etc
	; Poly 5+17
	.byte	$4D, $4E, $4F, $15, $7E, $7F
	.byte	$00, $00	; d"  "
	; Poly 5
	.byte	$4D, $4E, $4F
	.byte	$15, $00, $00, $00, $00	; d"5    "
	; Poly 5+4
	.byte	$4D, $4E, $4F
	.byte	$15, $0B, $14, $00, $00	; d"5+4  "
	; Poly 5
	.byte	$4D, $4E, $4F
	.byte	$15, $00, $00, $00, $00	; d"5    "
	; Poly 17
	.byte	$4D, $4E, $4F
	.byte	$11, $17, $00, $00, $00	; d"17   "
	.byte	$30, $75, $72, $65, $00, $00, $00, $00	; d"Pure    "	; Pure
	; Poly 4
	.byte	$4D, $4E, $4F
	.byte	$14, $00, $00, $00, $00	; d"4    "
	.byte	$30, $75, $72, $65, $00, $00, $00, $00	; d"Pure    "	; Pure

	; Poly 5+9
	.byte	$4D, $4E, $4F
	.byte	$15, $0B, $19, $00, $00	; d"5+9  "
	; Poly 5
	.byte	$4D, $4E, $4F
	.byte	$15, $00, $00, $00, $00	; d"5    "
	; Poly 5+4
	.byte	$4D, $4E, $4F
	.byte	$15, $0B, $14, $00, $00	; d"5+4  "
	; Poly 5
	.byte	$4D, $4E, $4F
	.byte	$15, $00, $00, $00, $00	; d"5    "
	; Poly 9
	.byte	$4D, $4E, $4F
	.byte	$19, $00, $00, $00, $00	; d"9    "
	.byte	$30, $75, $72, $65, $00, $00, $00, $00	; d"Pure    "	; Pure
	; Poly 4
	.byte	$4D, $4E, $4F
	.byte	$14, $00, $00, $00, $00	; d"4    "
	.byte	$30, $75, $72, $65, $00, $00, $00, $00	; d"Pure    "	; Pure

	.byte	$36, $6F, $6C, $00, $2F, $6E, $6C, $79	; d"Vol Only"	; Volume Only mode

; AUDCTL values used for some specific modes like 16-bit, clock, etc

ctlcmp = *
	.byte	$40, $10, $20, $08, $40, $10, $20, $08
ctlval = *
	.byte	8, 12, 8, 12, 8, 12, 8, 12

; music notes and other text strings

.if DISPLAYNOTES=1

txt_notes_noise = *
	.byte	$50, $51, $52, $53	; display 'Noise' when the notes cannot be identified from Distortion 0 or 8

txt_notes_off = *
	.byte	$2F, $66, $66, $00	; d"Off "	; display 'Off' when silence is detected, useful for channels being unused

; musical notes, this could be a lot better but it works for now
; ideally, note and octave are separate, but I don't know how to do this just yet

txt_notes_oct0 = *
	.byte	$23, $0D, $10, $00, $23, $03, $10, $00, $24, $0D, $10, $00, $24, $03, $10, $00, $25, $0D, $10, $00, $26, $0D, $10, $00, $26, $03, $10, $00, $27, $0D, $10, $00, $27, $03, $10, $00, $21, $0D, $10, $00, $21, $03, $10, $00, $22, $0D, $10, $00	; d"C-0 C#0 D-0 D#0 E-0 F-0 F#0 G-0 G#0 A-0 A#0 B-0 "
txt_notes_oct1 = *
	.byte	$23, $0D, $11, $00, $23, $03, $11, $00, $24, $0D, $11, $00, $24, $03, $11, $00, $25, $0D, $11, $00, $26, $0D, $11, $00, $26, $03, $11, $00, $27, $0D, $11, $00, $27, $03, $11, $00, $21, $0D, $11, $00, $21, $03, $11, $00, $22, $0D, $11, $00	; d"C-1 C#1 D-1 D#1 E-1 F-1 F#1 G-1 G#1 A-1 A#1 B-1 "
txt_notes_oct2 = *
	.byte	$23, $0D, $12, $00, $23, $03, $12, $00, $24, $0D, $12, $00, $24, $03, $12, $00, $25, $0D, $12, $00, $26, $0D, $12, $00, $26, $03, $12, $00, $27, $0D, $12, $00, $27, $03, $12, $00, $21, $0D, $12, $00, $21, $03, $12, $00, $22, $0D, $12, $00	; d"C-2 C#2 D-2 D#2 E-2 F-2 F#2 G-2 G#2 A-2 A#2 B-2 "
txt_notes_oct3 = *
	.byte	$23, $0D, $13, $00, $23, $03, $13, $00, $24, $0D, $13, $00, $24, $03, $13, $00, $25, $0D, $13, $00, $26, $0D, $13, $00, $26, $03, $13, $00, $27, $0D, $13, $00, $27, $03, $13, $00, $21, $0D, $13, $00, $21, $03, $13, $00, $22, $0D, $13, $00	; d"C-3 C#3 D-3 D#3 E-3 F-3 F#3 G-3 G#3 A-3 A#3 B-3 "
txt_notes_oct4 = *
	.byte	$23, $0D, $14, $00, $23, $03, $14, $00, $24, $0D, $14, $00, $24, $03, $14, $00, $25, $0D, $14, $00, $26, $0D, $14, $00, $26, $03, $14, $00, $27, $0D, $14, $00, $27, $03, $14, $00, $21, $0D, $14, $00, $21, $03, $14, $00, $22, $0D, $14, $00	; d"C-4 C#4 D-4 D#4 E-4 F-4 F#4 G-4 G#4 A-4 A#4 B-4 "
txt_notes_oct5 = *
	.byte	$23, $0D, $15, $00, $23, $03, $15, $00, $24, $0D, $15, $00, $24, $03, $15, $00, $25, $0D, $15, $00, $26, $0D, $15, $00, $26, $03, $15, $00, $27, $0D, $15, $00, $27, $03, $15, $00, $21, $0D, $15, $00, $21, $03, $15, $00, $22, $0D, $15, $00	; d"C-5 C#5 D-5 D#5 E-5 F-5 F#5 G-5 G#5 A-5 A#5 B-5 "
	.byte	$23, $0D, $16, $00, $23, $03, $16, $00, $24, $0D, $16, $00, $24, $03, $16, $00, $25, $0D, $16, $00, $26, $0D, $16, $00, $26, $03, $16, $00, $27, $0D, $16, $00, $27, $03, $16, $00, $21, $0D, $16, $00, $21, $03, $16, $00, $22, $0D, $16, $00	; d"C-6 C#6 D-6 D#6 E-6 F-6 F#6 G-6 G#6 A-6 A#6 B-6 "
	.byte	$23, $0D, $17, $00, $23, $03, $17, $00, $24, $0D, $17, $00, $24, $03, $17, $00, $25, $0D, $17, $00, $26, $0D, $17, $00, $26, $03, $17, $00, $27, $0D, $17, $00, $27, $03, $17, $00, $21, $0D, $17, $00, $21, $03, $17, $00, $22, $0D, $17, $00	; d"C-7 C#7 D-7 D#7 E-7 F-7 F#7 G-7 G#7 A-7 A#7 B-7 "
	.byte	$23, $0D, $18, $00, $23, $03, $18, $00, $24, $0D, $18, $00, $24, $03, $18, $00, $25, $0D, $18, $00, $26, $0D, $18, $00, $26, $03, $18, $00, $27, $0D, $18, $00, $27, $03, $18, $00, $21, $0D, $18, $00, $21, $03, $18, $00, $22, $0D, $18, $00	; d"C-8 C#8 D-8 D#8 E-8 F-8 F#8 G-8 G#8 A-8 A#8 B-8 "
	.byte	$23, $0D, $19, $00, $23, $03, $19, $00, $24, $0D, $19, $00, $24, $03, $19, $00, $25, $0D, $19, $00, $26, $0D, $19, $00, $26, $03, $19, $00, $27, $0D, $19, $00, $27, $03, $19, $00, $21, $0D, $19, $00, $21, $03, $19, $00, $22, $0D, $19, $00	; d"C-9 C#9 D-9 D#9 E-9 F-9 F#9 G-9 G#9 A-9 A#9 B-9 "
	.byte	$23, $0D, $11, $10, $23, $03, $11, $10, $24, $0D, $11, $10, $24, $03, $11, $10	; d"C-10C#10D-10D#10"	; last frequency

	;dta d"C- C# D- D# E- F- F# G- G# A- A# B- "

; lookup table for identifying AUDF values and its matching note to display, each dta line is 64 bytes long
; notes and frequencies are in reverse order, so 00 is the highest frequency, but also the lowest note, usually C-1 in RMT

	ORG	VISDATA+$400	; a new page after the text above (it no longer fits in $300 bytes)

txt_dist_2_179mhz_freqs = *

	.byte	$3F, $3E, $3C, $3B, $38, $36, $34, $33, $31, $30, $2F, $2E, $2D, $2C, $2B, $2A	; 00 to 0F
	.byte	$29, $29, $28, $27, $26, $25, $25, $24, $23, $23, $22, $22, $21, $21, $20, $20	; 10 to 1F
	.byte	$1F, $1F, $1E, $1E, $1E, $1D, $1D, $1C, $1C, $1B, $1B, $1B, $1A, $1A, $1A, $19	; 20 to 2F
	.byte	$19, $18, $18, $18, $17, $17, $17, $17, $16, $16, $16, $15, $15, $15, $15, $14	; 30 to 3F
	.byte	$14, $14, $14, $13, $13, $13, $13, $12, $12, $12, $12, $11, $11, $11, $11, $11	; 40 to 4F
	.byte	$10, $10, $10, $10, $10, $0F, $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0E, $0E, $0E	; 50 to 5F
	.byte	$0D, $0D, $0D, $0D, $0D, $0C, $0C, $0C, $0C, $0C, $0C, $0B, $0B, $0B, $0B, $0B	; 60 to 6F
	.byte	$0B, $0B, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $09, $09, $09, $09, $09, $09, $09	; 70 to 7F
	.byte	$08, $08, $08, $08, $08, $08, $08, $07, $07, $07, $07, $07, $07, $07, $07, $06	; 80 to 8F
	.byte	$06, $06, $06, $06, $06, $06, $06, $06, $05, $05, $05, $05, $05, $05, $05, $05	; 90 to 9F
	.byte	$05, $04, $04, $04, $04, $04, $04, $04, $04, $04, $04, $03, $03, $03, $03, $03	; A0 to AF
	.byte	$03, $03, $03, $03, $02, $03, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02	; B0 to BF
	.byte	$01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00	; C0 to CF
	.byte	$00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; D0 to DF
	.byte	$00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; E0 to EF
	.byte	$00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; F0 to FF

txt_dist_a_64khz_freqs = *	; FF is used for the missing B-2

	.byte	$3F, $3F, $3F, $3F, $3F, $3F, $3D, $3A, $39, $37, $35, $34, $32, $31, $30, $2F	; 00 to 0F
	.byte	$2E, $2D, $2C, $2B, $2A, $29, $29, $28, $27, $26, $26, $25, $25, $24, $24, $23	; 10 to 1F
	.byte	$23, $22, $22, $21, $21, $20, $20, $1F, $1F, $1E, $1E, $1E, $1D, $1D, $1C, $1C	; 20 to 2F
	.byte	$1C, $1B, $1B, $1B, $1A, $1A, $1a, $19, $19, $19, $18, $18, $18, $17, $17, $17	; 30 to 3F
	.byte	$17, $16, $16, $16, $16, $15, $15, $15, $15, $14, $14, $14, $14, $13, $13, $13	; 40 to 4F
	.byte	$13, $13, $12, $12, $12, $12, $11, $11, $11, $11, $11, $11, $10, $10, $10, $10	; 50 to 5F
	.byte	$10, $0F, $0F, $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0E, $0E, $0E, $0D, $0D, $0D	; 60 to 6F
	.byte	$0D, $0D, $0D, $0C, $0C, $0C, $0C, $0C, $0C, $0C, $0B, $0B, $0B, $0B, $0B, $0B	; 70 to 7F
	.byte	$0B, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $09, $09, $09, $09, $09, $09, $09	; 80 to 8F
	.byte	$09, $08, $08, $08, $08, $08, $08, $08, $08, $07, $07, $07, $07, $07, $07, $07	; 90 to 9F
	.byte	$07, $07, $06, $06, $06, $06, $06, $06, $06, $06, $06, $06, $05, $05, $05, $05	; A0 to AF
	.byte	$05, $05, $05, $05, $05, $05, $04, $04, $04, $04, $04, $04, $04, $04, $04, $04	; B0 to BF
	.byte	$04, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $02, $02, $02, $02	; C0 to CF
	.byte	$02, $02, $02, $02, $02, $02, $02, $02, $01, $01, $01, $01, $01, $01, $01, $01	; D0 to DF
	.byte	$01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; E0 to EF
	.byte	$00, $00, $00, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF	; F0 to FF

txt_dist_a_15khz_freqs = *	; FF is used for the missing B-0

	.byte	$3F, $3F, $3F, $3F, $3F, $3F, $3D, $3A, $39, $37, $35, $34, $32, $31, $30, $2F	; 00 to 0F
	.byte	$2E, $2D, $2C, $2B, $2A, $29, $28, $28, $27, $26, $26, $25, $24, $24, $23, $23	; 10 to 1F
	.byte	$22, $22, $21, $21, $20, $20, $1F, $1F, $1F, $1E, $1E, $1D, $1D, $1C, $1C, $1C	; 20 to 2F
	.byte	$1B, $1B, $1B, $1A, $1A, $1A, $19, $19, $19, $18, $18, $18, $17, $17, $17, $17	; 30 to 3F
	.byte	$16, $16, $16, $16, $15, $15, $15, $14, $14, $14, $14, $14, $13, $13, $13, $13	; 40 to 4F
	.byte	$12, $12, $12, $12, $12, $11, $11, $11, $11, $11, $10, $10, $10, $10, $10, $0F	; 50 to 5F
	.byte	$0F, $0F, $0F, $0F, $0F, $0E, $0E, $0E, $0E, $0E, $0E, $0D, $0D, $0D, $0D, $0D	; 60 to 6F
	.byte	$0D, $0C, $0C, $0C, $0C, $0C, $0C, $0C, $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0A	; 70 to 7F
	.byte	$0A, $0A, $0A, $0A, $0A, $0A, $09, $09, $09, $09, $09, $09, $09, $09, $08, $08	; 80 to 8F
	.byte	$08, $08, $08, $08, $08, $08, $08, $07, $07, $07, $07, $07, $07, $07, $07, $06	; 90 to 9F
	.byte	$06, $06, $06, $06, $06, $06, $06, $06, $06, $05, $05, $05, $05, $05, $05, $05	; A0 to AF
	.byte	$05, $05, $05, $04, $04, $04, $04, $04, $04, $04, $04, $04, $04, $03, $03, $03	; B0 to BF
	.byte	$03, $03, $03, $03, $03, $03, $03, $03, $03, $02, $02, $02, $02, $02, $02, $02	; C0 to CF
	.byte	$02, $02, $02, $02, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01	; D0 to DF
	.byte	$01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FF	; E0 to EF
	.byte	$FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF	; F0 to FF

txt_dist_c_64khz_freqs = *	; FF is placeholder for now...

	.byte	$FF, $FF, $FF, $FF, $FF, $FF, $FF, $3C, $FF, $FF, $37, $FF, $34, $32, $FF, $30	; 00 to 0F
	.byte	$2F, $FF, $2D, $FF, $FF, $2B, $2A, $3C, $FF, $28, $3A, $27, $26, $FF, $25, $24	; 10 to 1F
	.byte	$37, $23, $FF, $35, $22, $21, $34, $FF, $20, $32, $1F, $FF, $FF, $1E, $FF, $30	; 20 to 2F
	.byte	$1D, $FF, $2F, $1C, $1B, $2E, $FF, $FF, $2D, $1A, $FF, $FF, $19, $FF, $2C, $18	; 30 to 3F
	.byte	$FF, $2B, $FF, $17, $2A, $FF, $FF, $29, $16, $FF, $FF, $FF, $15, $28, $FF, $FF	; 40 to 4F
	.byte	$27, $14, $FF, $FF, $FF, $13, $26, $FF, $FF, $FF, $12, $FF, $25, $FF, $FF, $24	; 50 to 5F
	.byte	$11, $FF, $FF, $FF, $FF, $23, $10, $FF, $FF, $FF, $FF, $22, $0F, $FF, $FF, $FF	; 60 to 6F
	.byte	$FF, $21, $FF, $0E, $FF, $FF, $FF, $FF, $FF, $0D, $20, $FF, $FF, $FF, $FF, $0C	; 70 to 7F
	.byte	$1F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $0B, $1E, $FF, $FF, $FF, $FF, $FF, $1D	; 80 to 8F
	.byte	$FF, $0A, $FF, $FF, $FF, $FF, $FF, $FF, $1C, $09, $FF, $FF, $FF, $FF, $FF, $FF	; 90 to 9F
	.byte	$FF, $1B, $08, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $1A, $07, $FF, $FF, $FF, $FF	; A0 to AF
	.byte	$FF, $FF, $FF, $FF, $FF, $06, $19, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $18	; B0 to BF
	.byte	$05, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $17, $FF, $04, $FF, $FF	; C0 to CF
	.byte	$FF, $FF, $FF, $FF, $FF, $FF, $FF, $16, $03, $FF, $FF, $FF, $FF, $FF, $FF, $FF	; D0 to DF
	.byte	$FF, $FF, $FF, $FF, $02, $FF, $15, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF	; E0 to EF
	.byte	$FF, $FF, $14, $01, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00	; F0 to FF

.endif

; infos position on screen

infoposLo = *
	; :8 dta <[scr+#*120+40]
	.repeat 8, I
	.byte	<(scr+I*120+40)
	.endrep
infoposHi = *
	; :8 dta >[scr+#*120+40]
	.repeat 8, I
	.byte	>(scr+I*120+40)
	.endrep

; display lists related stuff

dlist = *
	.byte	$70, $70, $30
	.byte	$42
	.word	scr
	; :11 dta $02
	.repeat 11, I
	.byte	$02
	.endrep
	.byte	$82
	; :12 dta $02
	.repeat 12, I
	.byte	$02
	.endrep
	.byte	$41
	.word	dlist

; some extra vbi data

; line counter spacing table for instrument speed from 1 to 6
tabpp = *
	.byte	156, 78, 52, 39, 19, 9, 4

;fixP 		dta 0

;tabppFixP  	dta 0,0,0,0,$80,$c0,$e0         ; adjustments for music speed

; old data used for buffered frame updates as references

oldvbi = *
	.word	0

; song timer, songline position and channel volumes of the current frame (before old_memory, which start_flush fills)

v_frame = *
	ORG	*+1
v_second = *
	ORG	*+1
v_minute = *
	ORG	*+1
v_region = *
	ORG	*+1
v_ord = *
	ORG	*+1
v_volume = *
	ORG	*+TRACKS

old_memory = *

old_ord = *
	ORG	*+1
old_abeat = *
	ORG	*+1
old_second = *
	ORG	*+1
old_minute = *
	ORG	*+1
old_audf = *
	ORG	*+TRACKS
old_audc = *
	ORG	*+TRACKS
;old_note     	org *+TRACKS
; yes that's shit but I cannot find a better way around for now...
old_off = *
	ORG	*+TRACKS
old_volume = *
	ORG	*+TRACKS
old_speed = *
	ORG	*+1
old_audctl = *
	ORG	*+1
old_skctl = *
	ORG	*+1

.if STEREOMODE=1
old_audctl2 = *
	ORG	*+1
old_skctl2 = *
	ORG	*+1
.endif

; temporary missiles location

mistmp = *
	ORG	*+TRACKS

; load font into memory, this was put at the very end to avoid overwriting other data

	ORG	FONT	; characters set memory location
	.incbin "font.fnt"	; some cool looking font
	RUN	start
	OPT_H	0	; RMT module is standard Atari binary file already
	.incbin "music.rmt"	; include music RMT module
	OPT_H	1

; that's all... ;-)

