; sap.s - ca65 version of asm/Patch-16/sap.asm
; Generated by scripts/mads2ca65.py: edit the MADS source and run the script again.

;***************************************************************************************************************;
;* Simple RMT2SAP Creator                                                                                      *;
;* By VinsCool, 05-10-2021                                                                                     *;
;* Based on the SAP specs listed at https://asap.sourceforge.net/sap-format.html                               *;
;*                                                                                                             *;
;* Include with Simple RMT Player (dasmplayer.asm) to export .sap files instead of Atari executables (.obx)    *;
;* Edit the text with the information you want, a maximum of 120 characters per argument is supported          *;
;* Use "<?>" for unknown values, although this is entirely optional, it's simply for the SAP format convention *;
;* SPACING is the CR/LF (Carriage Return, Line Feed) word, merely put this between each argument               *;
;***************************************************************************************************************;

SPACING = $0A0D

; SAP header

	ORG	$0000	; XASM yells at me without an ORG here... 
; SAP are the characters used to define the format at the start of every .sap file
SAP = *
	.byte	"SAP"
	.word	SPACING	; IMPORTANT, must be at the end of EVERY argument to generate proper SAP exports

; SAP arguments, not all are included but they could be if wanted
; if text needs to be inside quotation marks, the ' character will be used for delimiting

AUTHOR = *
	.byte	"AUTHOR "
	.byte	$22, $52, $61, $73, $74, $65, $72, $22	; c'"Raster"'
	.word	SPACING

NAME = *
	.byte	"NAME "
	.byte	$22, $49, $6D, $20, $73, $75, $72, $65, $22	; c'"Im sure"'
	.word	SPACING

DATE = *
	.byte	"DATE "
	.byte	$22, $43, $6F, $6E, $76, $65, $72, $74, $65, $64, $20, $30, $35, $2F, $31, $30, $2F, $32, $30, $32, $31, $22	; c'"Converted 05/10/2021"'
	.word	SPACING

SONGS = *	;dta c"SONGS "		; optional argument
	;dta c"3"
	;dta a(SPACING)

DEFSONG = *	;dta c"DEFSONG "	; optional argument
	;dta c"0"
	;dta a(SPACING)

.if STEREOMODE=1
STEREO = *
	.byte	"STEREO"
	.word	SPACING
.endif

	;IFT REGIONPLAYBACK==1	; optional argument, and useless in Altirra with my own hijacked stuff
NTSC = *	;dta c"NTSC"
	;dta a(SPACING)
	;EIF

TYPE = *
	.byte	"TYPE B"
	.word	SPACING

FASTPLAY = *
	;dta c"FASTPLAY "	; optional argument, and useless in Altirra with my own hijacked stuff
	;dta c"312"		; must be manually edited for now. 312 for PAL 50hz and 262 for NTSC 60hz are most common
	;dta a(SPACING)

; SAP init address, very important to have set up correctly, or else bad things happen
INIT = *
	.byte	"INIT "
	.byte	"3E00"	; the same address used for Simple RMT Player, because why not
	.word	SPACING

; rmtplay jump address
PLAYER_ = *
	.byte	"PLAYER "
	.byte	"3103"	; rmt_play = PLAYER+3, PLAYER is $3100 for the Simple RMT Player (FEAT_IS_SIMPLEP)
	.word	SPACING

TIME = *	;dta c"TIME "		; optional argument
	;dta c"69:42.00 "	; Minutes:Seconds.Miliseconds format
	;dta c"LOOP"		; optional
	;dta a(SPACING)

ENDHEADER = *
	.byte	$FF, $FF	; Atari header before assembly, very important to keep!

; and that's all :D

