#pragma once

#include "PlatformTypes.h"

#include <string>
#include <vector>

// The command table of the program - every menu item and toolbar button
// joined per command ID with its prompt from the STRINGTABLE of Rmt.rc - as a
// Markdown table: the script command "dump actions <file>" writes it (see
// doc/rmt_scripting.md). The Qt frontend collects the menu items and the
// buttons from its menu bar and toolbars (RmtDumpActions() in
// qt/RmtQtFrontend.cpp); this file only formats them, so it needs no Qt.
//
// The table doubles as a consistency check of the menus: a menu label that
// displays another key (after its tab) than the shortcut the item really has
// is an ERROR marker in the table.

struct TActionMenuItem {
    UINT id = 0;
    std::vector<std::string> path; // the menu texts above the item, "&File" ... as written
    std::string label;             // the item's text as written: "&Save\tCtrl+S"
    std::string key;               // the key the item really has ("Ctrl+S"), "" for none
};

struct TActionToolButton {
    UINT id = 0;
    std::string bar;    // "Main", "Block"
    std::string tip;    // the tooltip
    std::string status; // the status bar text
};

// The rows in the order they are met: menu items, then buttons without a menu item. errorCount: the ERROR markers.
std::string BuildActionTable(const std::vector<TActionMenuItem>& menuItems, const std::vector<TActionToolButton>& buttons, int& errorCount);

// The label without the mnemonic marker: "&File" is "File", "&&" is one "&", the key after the tab is not part of it.
std::string ActionPlainText(const std::string& menuText);

// The "status text\ntooltip" prompt of a command in the STRINGTABLE of Rmt.rc (generated by
// cmake/GeneratePrompts.cmake); nullptr for none.
const char* RmtFindPrompt(UINT id);
