# EmbedResources.cmake - compile the bitmaps of src/res into the program for
# the builds without MFC (no .rc resources there): generates a C++ file with
# one byte array per resource and RmtFindResource(), declared in CompatTypes.h.
#
#   rmt_embed_resources(<output.cpp> <ID> <file> [<ID> <file> ...])
#
# IDs are the names of src/resource.h.

function(rmt_embed_resources output)
    set(body "")
    set(table "")
    set(deps "")
    list(LENGTH ARGN n)
    math(EXPR last "${n} - 1")
    foreach(i RANGE 0 ${last} 2)
        math(EXPR j "${i} + 1")
        list(GET ARGN ${i} id)
        list(GET ARGN ${j} file)
        list(APPEND deps ${file})
        file(READ ${file} hex HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
        string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" hex "${hex}")
        get_filename_component(name ${file} NAME)
        string(APPEND body "// ${name}\nstatic const unsigned char res_${id}[] = {\n${hex}\n};\n\n")
        string(APPEND table "    { ${id}, res_${id}, sizeof(res_${id}) },\n")
    endforeach()
    set(content "// generated by cmake/EmbedResources.cmake - do not edit\n#include \"PlatformTypes.h\"\n#include \"resource.h\"\n\n${body}")
    string(APPEND content "static const struct { UINT id; const unsigned char* data; size_t size; } res_table[] = {\n${table}};\n\n")
    string(APPEND content "bool RmtFindResource(UINT id, const unsigned char** data, size_t* size)\n{\n    for (const auto& r : res_table)\n        if (r.id == id) { *data = r.data; *size = r.size; return true; }\n    return false;\n}\n")
    # rewrite only when changed, so the build does not recompile it every time
    if(EXISTS ${output})
        file(READ ${output} old)
    endif()
    if(NOT "${old}" STREQUAL "${content}")
        file(WRITE ${output} "${content}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${deps})
endfunction()
