# GeneratePrompts.cmake - the prompts of the STRINGTABLEs of src/Rmt.rc
# ("status text\ntooltip" per command ID) as a C++ table for the builds
# without a resource compiler, for the script command "dump actions"
# (ActionTable.cpp): generates a C++ file with RmtFindPrompt(), declared in
# ActionTable.h. Run at configure time; changing Rmt.rc re-runs CMake.
#
#   rmt_generate_prompts(<output.cpp> <Rmt.rc> <resource.h>)
#
# Only the command IDs (ID_...) that are defined (resource.h, or the MFC ones of MfcTypes.h) are taken.

function(rmt_generate_prompts output rc header)
    file(READ ${rc} rc_text)
    # a ';' would split the list of matches below
    string(REPLACE ";" "<SEMICOLON>" rc_text "${rc_text}")
    string(REGEX MATCHALL "[ \t]+ID_[A-Za-z0-9_]+[ \t]+\"[^\"\r\n]*\"" entries "${rc_text}")
    set(table "")
    foreach(entry IN LISTS entries)
        string(REGEX REPLACE "^[ \t]+(ID_[A-Za-z0-9_]+)[ \t]+(\".*\")$" "\\1;\\2" parts "${entry}")
        list(GET parts 0 id)
        list(GET parts 1 text)
        string(REPLACE "<SEMICOLON>" ";" text "${text}")
        string(APPEND table "#ifdef ${id}\n    { ${id}, ${text} },\n#endif\n")
    endforeach()
    set(content "// generated by cmake/GeneratePrompts.cmake - do not edit\n#include \"PlatformTypes.h\"\n#include \"ActionTable.h\"\n#include \"resource.h\"\n\n")
    string(APPEND content "static const struct { UINT id; const char* prompt; } prompt_table[] = {\n${table}    { 0, nullptr }\n};\n\n")
    string(APPEND content "const char* RmtFindPrompt(UINT id)\n{\n    for (const auto& p : prompt_table)\n        if (p.id == id) return p.prompt;\n    return nullptr;\n}\n")
    if(EXISTS ${output})
        file(READ ${output} old)
    endif()
    if(NOT "${old}" STREQUAL "${content}")
        file(WRITE ${output} "${content}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${rc} ${header})
endfunction()
